### ISSUE TITLE
Winston Logging Crash in 2.2.1

### ISSUE THREAD

**Issue by werkshy** [DataDog/dd-trace-js#1882] opened 2022-02-28 17:25 UTC
**Describe the bug**

We updated to 2.2.1 and our (NestJS/Node/Typescript) app is now dumping a stack trace when logging requests.

```
Feb 28 12:13:51.914 | api | api-worker | staging | at Reflect.decorate (/app/node_modules/reflect-metadata/Reflect.js:123:24)
-- | -- | -- | -- | --
  | Feb 28 12:13:51.914 | api | api-worker | staging | at DecorateProperty (/app/node_modules/reflect-metadata/Reflect.js:553:33)
  | Feb 28 12:13:51.914 | api | api-worker | staging | at /app/src/common/decorators/Traceable.js:40:16
  | Feb 28 12:13:51.914 | api | api-worker | staging | at Logger.debug (/app/src/common/logging/Logger.js:84:30)
  | Feb 28 12:13:51.914 | api | api-worker | staging | at DerivedLogger.<computed> [as debug] (/app/node_modules/winston/lib/winston/create-logger.js:95:19)
  | Feb 28 12:13:51.914 | api | api-worker | staging | at DerivedLogger.log (/app/node_modules/winston/lib/winston/logger.js:257:10)
  | Feb 28 12:13:51.914 | api | api-worker | staging | at DerivedLogger.<anonymous> (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/winston.js:17:15)
  | Feb 28 12:13:51.914 | api | api-worker | staging | at Channel.publish (node:diagnostics_channel:56:9)
  | Feb 28 12:13:51.914 | api | api-worker | staging | at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:13:9)
  | Feb 28 12:13:51.914 | api | api-worker | staging | at /app/node_modules/dd-trace/packages/dd-trace/src/plugins/log_plugin.js:39:46
  | Feb 28 12:13:51.914 | api | api-worker | staging | TypeError: Cannot read properties of undefined (reading 'span')
  | Feb 28 12:13:51.914 | api | api-worker | staging | {"source":"stderr","service":"api","timestamp":1646068431914}
  | Feb 28 12:13:51.914 | api | api-worker | staging | ^
  | Feb 28 12:13:51.914 | api | api-worker | staging | this.tracer.inject(storage.getStore().span, LOG, holder)
  | Feb 28 12:13:51.913 | api | api-worker | staging | /app/node_modules/dd-trace/packages/dd-trace/src/plugins/log_plugin.js:39
```

**Environment**

ECS (docker `FROM gcr.io/distroless/nodejs:16`)

* **Operation system:** `FROM gcr.io/distroless/nodejs:16`
* **Node version:** v16
* **Tracer version:** 2.2.1
* **Agent version:**

**Comment by rochdev** [comment] 2022-02-28 17:26
Closing as this is a duplicate of #1879. The fix will be in 2.3.0.

**Closed by rochdev** 2022-02-28 17:26 UTC
Labels: bug, integrations
