### ISSUE TITLE
Prebuilds for ARM

### ISSUE THREAD

**Issue by iveelsm** [DataDog/dd-trace-js#760] opened 2019-11-25 18:43 UTC
**Describe the bug**

When upgrading to GCC 8.+ on Debian systems in order to use C++ 17 functionality, a large number of warnings are output for the native code in dd-trace.

Warnings from my build logs:
```
make: Entering directory '/install/node_modules/dd-trace/build'
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/Collector.o
In file included from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Collector.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/Collector.cpp:1:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /root/.cache/node-gyp/10.17.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Collector.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/Collector.cpp:1:
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.17.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/EventLoop.o
In file included from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Collector.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/EventLoop.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/EventLoop.cpp:1:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /root/.cache/node-gyp/10.17.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Collector.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/EventLoop.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/EventLoop.cpp:1:
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.17.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/GarbageCollection.o
In file included from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Collector.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/GarbageCollection.hpp:8,
                 from ../packages/dd-trace/src/native/metrics/GarbageCollection.cpp:3:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../packages/dd-trace/src/native/metrics/GarbageCollection.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/GarbageCollection.cpp:3:
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.17.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/Heap.o
In file included from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Collector.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/Heap.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Heap.cpp:5:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../packages/dd-trace/src/native/metrics/Heap.cpp:3:
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.17.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/Histogram.o
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/Object.o
In file included from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Object.cpp:3:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /root/.cache/node-gyp/10.17.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Object.cpp:3:
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.17.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/Process.o
In file included from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Collector.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/Process.hpp:5,
                 from ../packages/dd-trace/src/native/metrics/Process.cpp:1:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /root/.cache/node-gyp/10.17.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Collector.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/Process.hpp:5,
                 from ../packages/dd-trace/src/native/metrics/Process.cpp:1:
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.17.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/SpanTracker.o
In file included from ../packages/dd-trace/src/native/metrics/Object.hpp:3,
                 from ../packages/dd-trace/src/native/metrics/Collector.hpp:6,
                 from ../packages/dd-trace/src/native/metrics/SpanTracker.hpp:7,
                 from ../packages/dd-trace/src/native/metrics/SpanTracker.cpp:1:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../packages/dd-trace/src/native/metrics/SpanTracker.hpp:5,
                 from ../packages/dd-trace/src/native/metrics/SpanTracker.cpp:1:
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.17.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = datadog::SpanHandle; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<datadog::SpanHandle>&)]':
../packages/dd-trace/src/native/metrics/SpanTracker.cpp:67:80:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<datadog::SpanHandle>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<datadog::SpanHandle>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/utils.o
In file included from ../packages/dd-trace/src/native/metrics/utils.cpp:1:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /root/.cache/node-gyp/10.17.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../packages/dd-trace/src/native/metrics/utils.cpp:1:
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.17.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  CXX(target) Release/obj.target/metrics/packages/dd-trace/src/native/metrics/main.o
In file included from ../packages/dd-trace/src/native/metrics/main.cpp:1:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../../nan/nan.h:53,
                 from ../packages/dd-trace/src/native/metrics/main.cpp:1:
../packages/dd-trace/src/native/metrics/main.cpp: At global scope:
/root/.cache/node-gyp/10.17.0/include/node/node.h:573:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
  573 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/10.17.0/include/node/node.h:607:3: note: in expansion of macro 'NODE_MODULE_X'
  607 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../packages/dd-trace/src/native/metrics/main.cpp:78:3: note: in expansion of macro 'NODE_MODULE'
   78 |   NODE_MODULE(metrics, init);
      |   ^~~~~~~~~~~
In file included from /root/.cache/node-gyp/10.17.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../packages/dd-trace/src/native/metrics/main.cpp:1:
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/10.17.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.17.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/metrics.node
  COPY Release/metrics.node
make: Leaving directory '/install/node_modules/dd-trace/build'
```

**Environment**

* **Operation system: Debian 9**
* **Node version: v 10.15.1**
* **Tracer version: v 0.15.2**
* **Agent version: N/A**

**Comment by rochdev** [comment] 2019-11-25 20:26
Are you forcing building from source? We provide prebuilt binaries for the library, so it should never happen that it builds locally unless you are using an unsupported architecture (i.e. ARM) or explicitly force building from source.

Either way, this is still an issue since it should also build properly on any platform/architecture, but it should almost never happen so I wonder if there is another issue as well.

**Comment by msleevi** [comment] 2019-11-25 20:42
I think in this case, the build was running with `ARM`, but I do see this on my Macbook which is running `x86`. I don't explicitly do anything to force the build from source, as far as I know.

**Comment by rochdev** [comment] 2019-11-25 20:52
> I think in this case, the build was running with ARM.

That would explain why it's building on this environment. We've had similar warnings in the past on other platforms like Windows, so the warning itself is most likely not related to the architecture. I'll have to look into it.

> I do see this on my Macbook which is running x86. 

Can you try to upgrade to 0.16.1? We slightly changed how we build the native extension in 0.16.0 to account for older targets, but it's possible that it helps for newer targets as well. I'm also in the process of making further improvements.

Also, do you see a file on your MacBook in your project at `node_modules/dd-trace/prebuilds/darwin-x64/node-64.node`?

**Comment by msleevi** [comment] 2019-11-25 21:11
> Can you try to upgrade to 0.16.1? We slightly changed how we build the native extension in 0.16.0 to account for older targets, but it's possible that it helps for newer targets as well. I'm also in the process of making further improvements.

I have been meaning to do that upgrade, I can tack it on to these changes.

> Also, do you see a file on your MacBook in your project at node_modules/dd-trace/prebuilds/darwin-x64/node-64.node?

No, I do not.

**Comment by rochdev** [comment] 2019-11-25 21:17
In general, the possible reasons for building from source are:

* The current target platform cannot be found. This should not be the case on your MacBook (Pro I'm assuming) since it's supported.
* The `--build-from-source` flag is used on `npm install`.
* The `DD_NATIVE_METRICS=false` environment variable is set on `npm install`.
* The project itself is in a folder where there is a parent folder named `node_modules` in the tree.

Can you validate if one of the above is true?

**Comment by msleevi** [comment] 2019-11-25 21:29
Yeah! We run `npm rebuild` on the dev machines a fair bit, and the target platform is different on the CI system (ARM).

**Comment by rochdev** [comment] 2019-11-25 21:30
Ok, this explains the rebuild. I'll have to look into the warnings.

**Comment by rochdev** [comment] 2021-04-23 18:10
Since the issue is only warnings which are almost unavoidable because of backward compatibility I will change this to a feature request for ARM prebuilds which will remove the need to rebuild and thus remove the warnings when implemented.

**Comment by rochdev** [comment] 2022-07-18 17:43
Closing as ARM prebuilds are now published for Linux and macOS

**Closed by rochdev** 2022-07-18 17:43 UTC
Labels: core, community, feature-request
