### ISSUE TITLE
`dd-trace` not working properly with `native ES modules`

### ISSUE THREAD

**Issue by ahmedelshenawy25** [DataDog/dd-trace-js#1474] opened 2021-07-06 18:36 UTC
**Describe the bug**

I'm using `dd-trace` and `express.js` with `native ES modules` and there are some differences from `CommonJS`.
Instead of getting the route url as a resource name I get the http method.
![image](https://user-images.githubusercontent.com/26045307/124648021-ff065d80-de96-11eb-848e-662ca32fb6e5.png)
I used express hook to fix that:
```js
// datadog.tracer.js
import tracer from 'dd-trace';

tracer.init({
  logInjection: true,
  env: process.env.NODE_ENV
});

export default tracer;
```

```js
// server.js
import tracer from './datadog.tracer.js';

tracer.use('express', {
  hooks: {
    request: (span, req, res) => {
      span.setTag('http.route', req.route?.path || req.originalUrl);

      if (req.method === 'OPTIONS') {
        span.setTag('manual.drop');
      }
    }
  }
});
```
![image](https://user-images.githubusercontent.com/26045307/124648091-19403b80-de97-11eb-89aa-72521d7fe781.png)

But there are still some issues like `ioredis` not working with tracer even after enabling it manually `tracer.use('ioredis', { enabled: true });` and sometimes mongoose queries are not reflected in flame graph for the same endpoint
![image](https://user-images.githubusercontent.com/26045307/124649609-03337a80-de99-11eb-88de-6ca6909a7b65.png)
![image](https://user-images.githubusercontent.com/26045307/124649796-3bd35400-de99-11eb-8945-cdc06ee8a89c.png)

**Environment**

* **Operation system:**
Windows 10 19043.1081
* **Node version:**
14.15.5
* **Tracer version:**
0.35.0
* **Agent version:**
7.29.0

**Comment by rochdev** [comment] 2021-07-06 21:07
Duplicate of #349. We will be working on this in the coming weeks.

**Closed by rochdev** 2021-07-06 21:07 UTC
Labels: bug

**Comment by bengl** [comment] 2021-09-15 21:35
Experimental support for ESM is in `dd-trace@>=1.3.0`. Simply add the loader hook hook using the following CLI argument to Node.js.

`--experimental-loader dd-trace/loader-hook.mjs`

Please contact us directly at `support@datadoghq.com` if any issues arise.

**Comment by ahmedelshenawy25** [comment] 2021-09-15 22:14
Is there a way to set it through `init` method or an `env variable`?

**Comment by ahmedelshenawy25** [comment] 2021-09-16 16:26
Thanks @bengl
