### ISSUE TITLE
GraphQL plugins does not hook correctly.

### ISSUE THREAD

**Issue by quentin-** [DataDog/dd-trace-js#172] opened 2018-07-07 00:12 UTC
👋,

Unless i'm mistaking, the following should work:

```bash
yarn init
yarn add dd-trace@0.3.1 graphql@0.13.2
```

```index.js
// index.js
const tracer = require('dd-trace').init({ debug: true });
const graphql = require('graphql');

// Instrumented module "graphql/language/parser.js" was imported before calling tracer.init(). Please make sure to initialize the tracer before importing any instrumented module.
// Instrumented module "graphql/execution/execute.js" was imported before calling tracer.init(). Please make sure to initialize the tracer before importing any instrumented module.
```

node 8.9.4

edit: it actually hooked correctly despite the warnings, execution was failing because of https://github.com/DataDog/dd-trace-js/pull/173

**Comment by rochdev** [comment] 2018-07-09 14:13
This seems to be related to the fact that the module is required in `require-in-the-middle` before the plugin is patched. While this is the expected behavior, the current validation assumes this is not the case, causing the warning. You can safely ignore the warning for now, and this will be fixed in a future version by putting the validation earlier in the initialization process.

**Closed** 2018-07-17 14:05 UTC
Labels: bug, community, core
