### ISSUE TITLE
winston splat format is broken once dd-trace injects trace info

### ISSUE THREAD

**Issue by rburgst** [DataDog/dd-trace-js#817] opened 2020-01-07 20:12 UTC
**Describe the bug**

* **Sample repo**: https://github.com/rburgst/node-dd-winston

winston splat formatting is broken when dd-trace is run with trace injection.

Note that in the case where no trace/span info is available, logging works fine.

```
{"level":"debug","message":"Listening on port 3000"}
{"dd":{"trace_id":"4563346942945093045","span_id":"3676527141306563943"},"level":"info","message":"new request with url %s"}
```

The first log line is fine (i.e. splat formatting works, but no trace id is available at this point).
The 2nd line we see that the splat format is no longer resolved.

**Environment**
Mac OSX Catalina

* **Operation system:** Mac OSX Catalina
* **Node version:** 12.13.0
* **Tracer version:** 0.16.3
* **Agent version:** N/A

**Comment by ericmustin** [comment] 2020-01-09 13:43
Hey all,

just chiming in here. Took a quick look here, the root cause here is that there are some non-enumerable `Symbol` properties on the `record` that gets passed into the `correlate` method

https://github.com/winstonjs/winston#streams-objectmode-and-info-objects

> 
> As a consumer you may add whatever properties you wish – _internal state is
> maintained by `Symbol` properties:_
> 
> - `Symbol.for('level')` _**(READ-ONLY)**:_ equal to `level` property.
>   **Is treated as immutable by all code.**
> - `Symbol.for('message'):` complete string message set by "finalizing formats":
>   - `json`
>   - `logstash`
>   - `printf`
>   - `prettyPrint`
>   - `simple`
> - `Symbol.for('splat')`: additional string interpolation arguments. _Used
>   exclusively by `splat()` format._
> 
> These Symbols are stored in another package: `triple-beam` so that all
> consumers of `logform` can have the same Symbol reference. i.e.:

`correlate` : https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/util/log.js#L7-L2

this method prepares a fresh object with the the current dd.trace_id/dd.span_id, iterates over the existing log record's key/value pairs, and applies them to the fresh object. However, as Symbols( including the one for splat) are non enumerable properties, they get missed during the iteration.

I'd be happy to push up a fix for this, some thoughts were:

- apply the `carrier` keys to the existing log record, as opposed to the other way around(_current behavior_). The tradeoff here is that it mutates the original record, which may be undesirable.

- add a defensive check for `Object.getOwnPropertySymbols(record)` , something like

```
    for (const key in record) {
      carrier[key] = record[key]
    }

    const symbols = Object.getOwnPropertySymbols(record)

    for (const symbol in symbols) { 
      carrier[symbols[symbol]] = record[symbols[symbol]
    }
```

**Comment by rochdev** [comment] 2020-01-09 16:25
@ericmustin We cannot mutate the existing record because it can cause issues like [this](https://github.com/DataDog/dd-trace-js/issues/523).

I really like your second approach for its simplicity though, but what if the symbol is from the prototype chain?

**Comment by ericmustin** [comment] 2020-01-09 17:12
@rochdev I suppose one would have to recurse up the prototype chain. [s/o](https://stackoverflow.com/a/55006988) has a nifty example to borrow from

```
function getAllPropertySymbols (obj) {
    const proto = Object.getPrototypeOf(obj);
    const inherited = (proto) ? getAllPropertySymbols(proto) : [];
    return [...new Set(Object.getOwnPropertySymbols(obj).concat(inherited))];
}

getAllPropertySymbols(record)
```

This may introduce some performance concerns though?

Alternatively, hardcoding the winston(and eventually any other supported loggers) specific symbols and passing them in as an additional optional argument to the utility function could be a route to take here.

**Comment by rochdev** [comment] 2020-01-09 20:04
@ericmustin I guess given the use case is for `winston` built-in symbols and not user-defined, your original approach would be enough.

**Comment by ericmustin** [comment] 2020-01-10 00:16
made a quick PR before heading off for the day, https://github.com/DataDog/dd-trace-js/pull/819, happy to followup on anything with a fresh set of eyes tmrw

**Comment by rburgst** [comment] 2020-01-10 05:56
I believe you  are trying to fix the wrong end here. I havent looked at all the code but from the structure it appears to me that `correlate` is used by multiple plugins. Therefore, this method cannot make any assumptions about the nature of the `record` object that is being passed in (after all `pino` might work completely different from `winston`). However, in https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-winston/src/index.js#L8 we know for certain that `chunk` is an object that can safely be mutated since its only the log record being written. IMHO it would make more sense to either create a 2nd `correlateWithMutation` object or add a default parameter to `correlate` to instruct it whether it is allowed to modify the passed in object.

**Comment by rburgst** [comment] 2020-01-10 06:01
As an aside I would like to mention that when using `pino` this problem does not happen.

**Comment by rochdev** [comment] 2020-01-11 00:05
@rburgst I agree with the general idea that we should make sure to patch each plugin in the best way possible for the plugin. However, I would prefer to not make any assumption about how the library works internally. This is basically what I did originally, which resulted in this [issue](https://github.com/DataDog/dd-trace-js/issues/523). I'd rather play it safe unless there is a strong argument to mutate the original record instead.

**Comment by rburgst** [comment] 2020-01-11 07:32
well another requirement for dd-trace IMHO is to have is little performance impact as possible. If a service generates a whole lot of logs then I dont want the DD instrumentation to cause performance degradation.

**Comment by rochdev** [comment] 2020-01-13 23:21
Fair enough. Since the main use case for log injection comes from the plugins and not direct usage by the user, maybe we could add an option to the tracer or the plugin?

**Closed** 2020-01-28 21:07 UTC
Labels: bug, community, core
