### ISSUE TITLE
wildcard paths are not handled properly in express (nodejs)

### ISSUE THREAD

**Issue by manvydasu** [DataDog/dd-trace-js#3283] opened 2023-06-22 19:03 UTC
Hello,

I have this code example.

`tracer.js`
```
const ddTrace = require('dd-trace');

ddTrace.use()

const tracer = ddTrace.init();

module.exports = tracer;

```

`index.js`
```
const tracer = require('./tracer');
const express = require('express');
const winston = require('winston');

tracer.use('express', {
  hooks: {
    request: (span, req, res) => {
      console.log(span);
    }
  }
})

const logger = winston.createLogger({
  level: 'info',
  format: winston.format.json(),
  defaultMeta: { service: 'test-service' },
  transports: [
    new winston.transports.Console({
      format: winston.format.simple(),
    })
  ],
});

const app = express();

app.get('/test', (req, res) => {
  logger.info('GET request to /test endpoint')

  res.send('GET request to /test endpoint')
})

app.get('*', (req, res) => {
  logger.info('GET request to /* endpoint')

  res.send('GET request to /* endpoint')
})

const port = 3000;

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

package versions
```
    "dd-trace": "^4.2.0",
    "express": "^4.18.2",
    "winston": "^3.9.0"
```

In the example above: 
whenever `/test` route is matched, span's value of `http.route`: is equal to `/test` (**correct**).
whenever any other route is matched (i.e. `/test-route`, span's value of `http.route`: is equal to empty string (**seems strange**).

Due to this, resource name is not visible in Datadog's UI, APM pages. 

Is this expected?

Seems like there was issue related to wildcard earlier, but it was closed https://github.com/DataDog/dd-trace-js/issues/477

Note: this example does not work when converted to ESM, but I see there already exists issue for that.

**Comment by mikael-mattsson** [comment] 2023-08-22 16:20
Hey,

I'm also experiencing this issue while running a Remix app using the Express adapter. Would very much appreciate it if this could be looked into.

**Comment by villanuevadani** [comment] 2023-08-23 11:13
Do you know whether this issue has been resolved in v4?

**Comment by brunojppb** [comment] 2023-08-23 11:26
@villanuevadani my reproduction case [here](https://github.com/DataDog/dd-trace-js/issues/3283#issuecomment-1653821725) is using the latest version (v4.8.1) and this still happens.

**Comment by rochdev** [comment] 2023-08-31 01:12
This is the expected behaviour. Basically, we use the route as configured on the router as the resource name. If there is no route, or the route is a global wildcard, then the resource name is empty. This is by design because the path might have unbounded cardinality, but routes always have a fixed number of possible values. For example, `/user/123` and `/user/456` would both match `/user/:id` and be grouped together, but if we used the path there could be millions of unique values that could not be grouped together.

If the paths are well known and there is a way to properly group them using knowledge about the app, this can be done manually with a span hook. This is useful for routers we don't support, like for example Remix, or for custom routers, or when the cardinality is known to be low.

For example:

```js
tracer.use('express', {
  hooks: {
    request: (span, req, res) {
      span.setTag('http.route', '/user/:id')
    }
  }
})
```

**Comment by rochdev** [comment] 2023-08-31 01:14
I will close this issue since the described behaviour is expected and there is a workaround when needed, but feel free to open a feature request for Remix specifically.

**Closed by rochdev** 2023-08-31 01:14 UTC
Labels: question, integration-express

**Comment by brunojppb** [comment] 2023-08-31 08:43
> This is the expected behaviour. Basically, we use the route as configured on the router as the resource name. If there is no route, or the route is a global wildcard, then the resource name is empty. This is by design because the path might have unbounded cardinality, but routes always have a fixed number of possible values. For example, `/user/123` and `/user/456` would both match `/user/:id` and be grouped together, but if we used the path there could be millions of unique values that could not be grouped together.
> 
> If the paths are well known and there is a way to properly group them using knowledge about the app, this can be done manually with a span hook. This is useful for routers we don't support, like for example Remix, or for custom routers, or when the cardinality is known to be low.
> 
> For example:
> 
> ```js
> tracer.use('express', {
>   hooks: {
>     request: (span, req, res) {
>       span.setTag('http.route', '/user/:id')
>     }
>   }
> })
> ```

Thanks @rochdev for the input on that.
Yeah, it makes sense and I was expecting this behaviour. I am mostly wondering if there is anything on the roadmap to support these new meta-frameworks like Remix and NextJS on the backend by leverage some sort of plugin.

Other than that, your suggesting is definitely a good way to workaround this given the Remix request handler hooked up to Express is a catch-all route (`'*'`).

Thanks again for the reply! 🙌

**Comment by rochdev** [comment] 2023-08-31 15:36
@brunojppb We're actively working on improvements for Next.js, but we don't currently have plans to support Remix. Please feel free to open a feature request with our [support](https://www.datadoghq.com/support/) team.

**Comment by brynary** [comment] 2023-11-17 00:44
Has anyone been successful using the request hook to appropriately set the `http.route` based on the Remix route that the server will invoke?

In other words, how to fill this in?:

```ts
tracer.use('express', {
  hooks: {
    request: (span, req, res) {
      const route = "???"; // Lookup the route filename based on the request URL?
      span.setTag('http.route', route)
    }
  }
})
```

**Comment by brunojppb** [comment] 2023-11-17 07:59
> Has anyone been successful using the request hook to appropriately set the `http.route` based on the Remix route that the server will invoke?
> 
> In other words, how to fill this in?:
> 
> ```ts
> tracer.use('express', {
>   hooks: {
>     request: (span, req, res) {
>       const route = "???"; // Lookup the route filename based on the request URL?
>       span.setTag('http.route', route)
>     }
>   }
> })
> ```

I'm still trying to figure this out.

With the Remix CLI we can at least output the list of paths the app support with:

```shell
npx @remix-run/dev routes --json
```

But I'm looking at how Remix is doing the route matching on the server and it looks like it needs the build artifacts in order to derive that as seen [here](https://github.com/remix-run/remix/blob/4912159f86f20ee552835be08239872ba8278c1b/packages/remix-server-runtime/server.ts#L105C9-L105C16) on the `remix-server-runtime` package:

```ts
export const createRequestHandler: CreateRequestHandlerFunction = (
  build,
  mode
) => {
  let _build: ServerBuild;
  let routes: ServerRoute[];
  let serverMode: ServerMode;
  let staticHandler: StaticHandler;
  let errorHandler: HandleErrorFunction;

  return async function requestHandler(
    request,
    loadContext = {},
    { __criticalCss: criticalCss } = {}
  ) {
    _build = typeof build === "function" ? await build() : build;
    if (typeof build === "function") {
      let derived = derive(_build, mode);
      routes = derived.routes;
      serverMode = derived.serverMode;
      staticHandler = derived.staticHandler;
      errorHandler = derived.errorHandler;
    } else if (!routes || !serverMode || !staticHandler || !errorHandler) {
      let derived = derive(_build, mode);
      routes = derived.routes;
      serverMode = derived.serverMode;
      staticHandler = derived.staticHandler;
      errorHandler = derived.errorHandler;
    }

    let url = new URL(request.url);

    let matches = matchServerRoutes(routes, url.pathname);
```

Still couldn't figure out a proper way to handle this. If one of you guys have more leads, I would really appreciate.

**Comment by brynary** [comment] 2023-11-18 18:32
@brunojppb I just asked ChatGPT4 and it pointed me to `matchPath` in React Router (https://v5.reactrouter.com/web/api/matchPath) which looks close to what we need

**Comment by brunojppb** [comment] 2023-11-27 15:09
> @brunojppb I just asked ChatGPT4 and it pointed me to `matchPath` in React Router (https://v5.reactrouter.com/web/api/matchPath) which looks close to what we need

@brynary that is interesting. I think combining the `matchPath` function with the routes generated by Remix via its CLI we might be able to pull off a little workaround for that. I'm going to try something out and report back.

**Comment by brunojppb** [comment] 2023-12-05 13:07
@brynary your suggestion of using `matchPath` works. Here is the gist:

#### Matching function to use in the dd hook

```ts
import { matchPath } from '@remix-run/react'
import fs from 'node:fs'
import * as path from 'node:path'

/**
 * Given a request path, tries to find a Remix route path pattern
 * that matches with an existing route in your Remix app.
 * 
 * Make sure to generate the Remix routes file during your build with:
 * 
 * ```shell
 * npx @remix-run/dev routes --json >> build/remix_routes.json
 * ```
 */
export function matchRemixRoutePattern(requestPath: string) {
  const routes = loadRoutesFile()
  for (const routePattern of routes) {
    if (matchPath(routePattern, requestPath) !== null) {
      return routePattern
    }
  }
  return null
}

let routesCache: string[] | null = null

function loadRoutesFile() {
  if (routesCache) {
    return routesCache
  }

  const buildFolder = path.resolve(process.cwd(), 'build')
  const routesData = fs.readFileSync(
    path.resolve(buildFolder, 'remix_routes.json'),
    { encoding: 'utf8', flag: 'r' }
  )
  const routesJson = JSON.parse(routesData)
  routesCache = flattenRoutes(routesJson)
  return routesCache!
}

function flattenRoutes(json: any[]) {
  let paths: string[] = []
  for (const entry of json) {
    if (entry.children) {
      const mappedPaths = flattenRoutes(entry.children)
        .filter(path => typeof path !== 'undefined')
        .map(path => `${entry.path}/${path}`)
      paths = [...paths, entry.path, ...mappedPaths]
    } else {
      paths.push(entry.path)
    }
  }

  return paths
}
```

#### Usage on the tracer hooks:

```ts
import tracer from 'dd-trace'
import { matchRemixRoutePattern } from './routeMatcher'

tracer.init()

tracer.use('express', {
  hooks: {
    request: (span, req, res) => {
      const referer = req?.headers['referer']
      if (referer) {
        try {
          const url = new URL(referer)
          const matchPattern = matchRemixRoutePattern(url.pathname)
          if (matchPattern) {
            span?.setTag('http.route', matchPattern)
          }
        } catch (error: unknown) {
          console.error('Invalid referer', error)
        }
      }
    },
  },
})

export default tracer
```

Although, I am now having troubles with dd-trace when I updated my Remix app to v2 and went full ESM. The hooks do not seem to trigger at all anymore for some reason.

This seems to be an known issue with ESM and the dd-trace lib: https://github.com/DataDog/dd-trace-js/issues/1863

**Comment by brunojppb** [comment] 2023-12-13 13:52
> @brynary your suggestion of using `matchPath` works. Here is the gist:
> 

Just managed to implement this on our apps and this seems to work fine with Datadog now:

![CleanShot 2023-12-13 at 14 49 39](https://github.com/DataDog/dd-trace-js/assets/2049560/ab0c88fe-f3d6-44fd-aade-b63a9c679390)

**Comment by brynary** [comment] 2023-12-13 14:16
@brunojppb nice, thanks for sharing!

**Comment by brunojppb** [comment] 2024-12-07 18:25
For folks still facing this limitation, I've published a little library that should help with that for now: 
- https://github.com/brunojppb/remix-datadog-express-tracing

We've been using it internally across several Remix apps for one year now without issues.

**Comment by jdnichollsc** [comment] 2025-03-20 21:49
Hey folks, hope you're doing well

Do you know what's the suggested way to integrate Datadog with React Router v7? 🤔

**Comment by brunojppb** [comment] 2025-03-24 14:28
> Hey folks, hope you're doing well
> 
> Do you know what's the suggested way to integrate Datadog dd-trace with React Router v7 for SSR with ExpressJS? 🤔
> 
> Thanks for your support! <3

Hey @jdnichollsc I believe there is no official support for it yet.
I've updated my library to support React Router 7 now: https://www.npmjs.com/package/react-router-datadog-express-tracing

**Comment by jdnichollsc** [comment] 2025-03-24 15:08
> > Hey folks, hope you're doing well
> > Do you know what's the suggested way to integrate Datadog dd-trace with React Router v7 for SSR with ExpressJS? 🤔
> > Thanks for your support! <3
> 
> Hey [@jdnichollsc](https://github.com/jdnichollsc) I believe there is no official support for it yet. I've updated my library to support React Router 7 now: https://www.npmjs.com/package/react-router-datadog-express-tracing

Oh wow, you're amazing Bruno! <3 Question, which version of ExpressJS are you using? I'm getting the below error from the terminal:
```
Found incompatible integration version: express@4.21.2
Starting development server
Started wall profiler in Main thread
Started space profiler in Main thread
Started events profiler in Main thread
Server is running on http://localhost:5173
```

**Comment by jdnichollsc** [comment] 2025-03-24 15:58
@brunojppb I added the **tracer.use** to debug from my project but's not working: https://github.com/DataDog/dd-trace-js/issues/5092#issuecomment-2748623912

**Comment by jdnichollsc** [comment] 2025-03-25 18:47
@brunojppb Thanks for your help! Ok, I was able to solve this error after moving the "tracer.use('express')" to the server/app.js
We're using this template for RR7 with SSR (Framework mode): https://github.com/remix-run/react-router-templates/tree/main/node-custom-server

Also, I didn't need to generate a JSON file for the routes, this was my implementation:

```ts
import { RouteConfigEntry } from "@react-router/dev/routes";
import { matchRoutes } from "react-router";
import routes from "@/routes";

// Extract the type from matchRoutes function parameter
type AgnosticRouteObject = Parameters<typeof matchRoutes>[0][0];

export function convertRouteConfig(entries: RouteConfigEntry[]): AgnosticRouteObject[] {
  return entries.map((entry) => {
    const routeObj: AgnosticRouteObject = {
      index: entry.index,
      path: entry.path,
      caseSensitive: entry.caseSensitive,
      id: entry.id,
    };
    if (entry.children) {
      routeObj.children = convertRouteConfig(entry.children);
    }
    return routeObj;
  });
}

tracer.use("express", {
  enabled: true,
  service: DD_TRACER_SERVICE_NAME,
  hooks: {
    request: (span, req, res) => {
      const host = req?.headers.host;
      // React Router adds .data to the URL sometimes, so we need to remove it
      const path = req?.url?.replace(".data", "");
      if (span && req?.url) {
        try {
          const url = new URL(`https://${host}${path}`);
          if (req.headers["x-correlation-id"]) {
            span.setTag("correlation_id", req.headers["x-correlation-id"]);
          }
          span.setTag("path", url.pathname);
          span.setTag("method", req.method);
          span.setTag("http.url", url.toString());
          const matches = matchRoutes(convertRouteConfig(routes), url.pathname);
          if (matches?.length) {
            span.setTag("http.route", matches?.at(-1)?.route.path);
          }

          if (res?.statusCode) {
            span.setTag("http.status_code", res?.statusCode);
          }
        } catch (error) {
          logger.error(error, "Error setting tags for Datadog");
        }
      }
    },
  },
});
``` 

Happy Coding! <3
