### ISSUE TITLE
Timeout Errors not  Displayed in Datadog Dashboard Despite Successful Reporting with DD_TRACE_DEBUG

### ISSUE THREAD

**Issue by vilakshan2996** [DataDog/dd-trace-js#4103] opened 2024-02-24 15:31 UTC
**Expected Behavior**

I expect that all test case errors, including timeouts, should be visible in the Datadog dashboard.

**Actual Behavior**

Timeout errors are not showing up in the Datadog dashboard, even though the traces are reported successfully, as indicated by the presence of `DD_TRACE_DEBUG` logs.

`DD_TRACE_DEBUG` output doesn't help much:

```
$ NODE_OPTIONS="-r dd-trace/ci/init" DD_ENV=ci DD_TRACE_DEBUG=true npx playwright test BO_Service.test.ts --project=$projectname

Extract from carrier: {"x-datadog-trace-id":"1176615104126108123","x-datadog-parent-id":"0000000000000000"}.
Running 1 test using 1 worker
Extract from carrier: {"x-datadog-trace-id":"617896122180169071","x-datadog-parent-id":"0000000000000000"}.

[1/1] [PROD] › BO_Service.test.ts:23:5 › UAT-TC-48: CC- Verify Get Customer Details with valid customerNumber
[PROD] › BO_Service.test.ts:23:5 › UAT-TC-48: CC- Verify Get Customer Details with valid customerNumber

Inject into carrier: {"x-datadog-trace-id":"3963407857172165997","x-datadog-parent-id":"3963407857172165997","x-datadog-sampling-priority":"1"}.

Flushing 0 metrics via HTTP
Flushing 0 metrics via HTTP
Flushing 0 metrics via HTTP

...

Encoding payload: [{"trace_id":"0893353fd6a3ed6f","span_id":"3bc39bf930498635","parent_id":"0000000000000000","name":"playwright.test","resource":"BO_Service.test.ts.UAT-TC-48: CC- Verify Get Customer Details with valid customerNumber","error":1,"meta":{"_dd.p.dm":"-4","service":"mena-prod","env":"ci","version":"1.0.0","...},"metrics":{"_dd.top_level":1,"_dd.rule_psr":1,"sampling.priority":1,...},"start":1708756519263642600,"duration":30021577393,"links":[],"service":"mena-prod","type":"test"},...]

...

Reporting results ...UAT-TC-48
Inject into carrier: {"x-datadog-trace-id":"7886921132486741761","x-datadog-parent-id":"7886921132486741761","x-datadog-sampling-priority":"1"}.

1) [PROD] › BO_Service.test.ts:23:5 › UAT-TC-48: CC- Verify Get Customer Details with valid customerNumber 
    "beforeAll" hook timeout of 30000ms exceeded.
...

Encoding payload: [{"trace_id":"6d73f8fbb964cf01","span_id":"6d73f8fbb964cf01","parent_id":"0000000000000000","name":"http.request","resource":"POST","error":0,"meta":{"_dd.p.tid":"65d98e4600000000","_dd.p.dm":"-0","service":"mena-prod","env":"ci","version":"1.0.0","...},"metrics":{"_dd.agent_psr":1,"_dd.top_level":1,"_dd.measured":1,...},"start":1708756550317011500,"duration":858751953,"links":[],"service":"mena-prod","type":"http"},...]

...

Request to the intake: {"path":"/api/v2/citestcycle","method":"POST","headers":{"Content-Type":"application/msgpack"},"timeout":15000,"url":"https://citestcycle-intake.datadoghq.com/"}
Response from the intake: {}

```

Environment

gitlab pipeline
Cloud Cl provider (Agentless)
playwright/test

**Comment by juan-fernandez** [comment] 2024-02-24 15:36
hey @vilakshan2996 , thanks for the report! Could you help with these details:

* dd-trace and playwright version you're using
* are the timeouts that are causing you issues happening in the `beforeAll` hooks? Or any kind of timeout
* when you say `Timeout errors are not showing up in the Datadog dashboard` you mean the test does not include an error message or the test failing does not include the error at all? 

Keep in mind that `beforeAll` hook does not belong to any specific test but to the suite: doesn't the error show up in the test suite?

**Comment by vilakshan2996** [comment] 2024-02-24 15:52
@playwright/test: v1.36.2
dd-trace : latest stable version  `npm install --save-dev dd-trace`

```
1) [PROD] › BO_Service.test.ts:23:5 › UAT-TC-48: CC- Verify Get Customer Details with valid customerNumber 
    "beforeAll" hook timeout of 30000ms exceeded.
      11 |
      12 |
    > 13 | test.beforeAll(async ({ playwright, baseURL }) => {
         |      ^
      14 |     await GetServerToken.getServerToken(playwright, baseURL);
      15 |     endpoint = JSON.parse(await apiActions.readValuesFromJSONFile('endpoints'))
      16 |     selectedDataSet = await funtionLibray.GetSelectDataSet();
```

yes, its happening in the `beforeAll` hook


In dashboard , I cannot see any entry regarding this error.
![image](https://github.com/DataDog/dd-trace-js/assets/73380111/b298f644-4f5a-4c3a-94de-e689bdd7eb6a)

I am able to view other entries, but the specific entry in question is not appearing in the Datadog dashboard.

**Comment by juan-fernandez** [comment] 2024-02-24 19:17
is the suite `BO_Service.test.ts:23:5` not showing up as errored either? You can select suites in the dropdown near the search bar: 

<img width="188" alt="Screenshot 2024-02-24 at 20 15 20" src="https://github.com/DataDog/dd-trace-js/assets/22798219/cb95ea9b-b31a-49a2-b650-9550655312ea">


> In dashboard , I cannot see any entry regarding this error.

ok so the test shows up but its status is `pass`. 

I'll try to reproduce this. A small reproducible case would go a long way to solve this more quickly 😄

**Comment by vilakshan2996** [comment] 2024-02-25 05:11
@juan-fernandez ,

Apologies for the delay. The specific suite is not visible in the results; although other suites have passed and are visible, this particular suite is not showing up.

**Comment by vilakshan2996** [comment] 2024-02-27 03:39
@juan-fernandez  any updates !!!

**Comment by juan-fernandez** [comment] 2024-02-27 08:05
> @juan-fernandez any updates !!!

hey! No updates, sorry. This might take a bit. A reproducible case would speed things up for sure 😄

**Comment by juan-fernandez** [comment] 2024-02-27 16:28
I'm pretty sure I found the root cause: https://github.com/DataDog/dd-trace-js/pull/4113. If you want you can test this fix by installing the branch: 

```
yarn add --dev dd-trace@https://github.com/DataDog/dd-trace-js/tarball/juan-fernandez/fix-empty-duration
```

You can see the changes for that branch in the PR or in https://github.com/DataDog/dd-trace-js/compare/juan-fernandez/fix-empty-duration 

I'll run some more tests and add some automatic e2e tests. I'll keep you posted

**Comment by juan-fernandez** [comment] 2024-02-29 07:49
the PR above is merged. I'll post here when we release it

**Closed** 2024-02-29 07:48 UTC
Labels: ci-app

**Comment by juan-fernandez** [comment] 2024-03-13 10:36
FYI, this should be released in https://github.com/DataDog/dd-trace-js/releases/tag/v5.6.0
