### ISSUE TITLE
TypeError: Cannot set property 'config' of undefined

### ISSUE THREAD

**Issue by TroyCoombs** [DataDog/dd-trace-js#684] opened 2019-09-18 14:23 UTC
**Describe the bug**
Updated to 0.15.0 yesterday and started getting this error.  If I disable 'plugins' within dd-trace init() and not enable and configure any plugins individually the error doesn't happen when the service receives a request.

Error is:
"TypeError: Cannot set property 'config' of undefined",
    "    at startSpan (D:\\Github\\applications\\node_modules\\dd-trace\\packages\\dd-trace\\src\\plugins\\util\\web.js:187:23)"
[stack trace.txt](https://github.com/DataDog/dd-trace-js/files/3627305/stack.trace.txt)

**Environment**
Restify V7.2.1

* **Operation system:**
Tested on both Windows 10 and Mac Mojave 10.14.6

* **Node version:**
10.16.0

* **Tracer version:**
0.15.0

* **Agent version:**
6.5.1

**Comment by rochdev** [comment] 2019-09-18 14:52
Can you share the entire stack trace? Also, what Web framework are you using?

**Comment by TroyCoombs** [comment] 2019-09-18 15:49
@rochdev  just added stack trace file and updated Environment section.

**Comment by rochdev** [comment] 2019-09-18 16:00
It looks like it's related to using HTTP2. I'll have to investigate further as we do not currently test support for this protocol.

**Comment by jimdubbs** [comment] 2019-09-18 19:28
@rochdev From what I can tell, the issue is here:

![image](https://user-images.githubusercontent.com/3068059/65179487-773b2f00-da35-11e9-8cbc-7d72dc191e41.png)

the check on if the req is a stream, req.stream._datadog is undefined at this point. In testing i simply commented out that if block and it appears to work fine now - but i dont totally understand what the purpose of it is.

**Comment by rochdev** [comment] 2019-09-18 20:59
The idea was to support HTTP2 since the structure of the request is different. By detecting HTTP2 using the `stream` property, we can set the tags using different headers and properties from `req`. However, the current implementation assumes the HTTP2 request was previously instrumented, which is not the case.

This is fixed in #688 which will be released in the next version.

**Comment by jimdubbs** [comment] 2019-09-18 21:13
Much Appreciated! Any idea on next anticipated release in terms of days/weeks?

**Comment by rochdev** [comment] 2019-09-18 21:18
I don't have a timeline, but it's definitely days and not weeks :smile:

**Closed** 2019-09-18 22:00 UTC
Labels: bug, community, core
