### ISSUE TITLE
Memory Leak in 2.7.1 when using Express tracing

### ISSUE THREAD

**Issue by jcarvalho** [DataDog/dd-trace-js#2082] opened 2022-05-26 14:32 UTC
Hi.

We have noticed a memory leak in our application after upgrading to version 2.7.1 (coming from version 2.5.0).

We have since done some digging, and we noticed the leak was only happening in our Web instances, so we tried to replicate the issue in a simple Express application, and successfully tracked it down to version 2.7.0 (where the Express instrumentation got re-written).

**Steps to reproduce**

Run the following application with `dd-trace` 2.7.0 or higher (using the latest version of `express`):

```javascript
const tracer = require('dd-trace')
tracer.init()

const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```
`package.json`:
```json
{
  "dependencies": {
    "dd-trace": "2.7.0",
    "express": "^4.18.1"
  }
}

```

Then, send traffic to the application (I used `ab -n 1000000 -c 10 http://localhost:3000`), and notice its used heap going up (until it eventually crashes with an OOM error).

Downgrading `dd-trace` to 2.6.0 solves the issue.

**Environment**

* **Operation system:** Linux
* **Node.js version:** 16.13.0
* **Tracer version:** 2.7.0 / 2.7.1
* **Agent version:** v7.32.4
* **Relevant library versions:** `express@4.18.1`

**Comment by eiselems** [comment] 2022-05-26 14:45
@jcarvalho could this be a duplicate of #2017 (please read the issue - title is misleading)?

**Comment by jcarvalho** [comment] 2022-05-26 14:49
Looks like it, yes :+1:

**Comment by rochdev** [comment] 2022-05-26 19:07
Closing this since it's a duplicate. Fix should be out soon.

**Closed by rochdev** 2022-05-26 19:07 UTC
Labels: bug
