### ISSUE TITLE
Club all service names with suffix to one without suffix

### ISSUE THREAD

**Issue by shubhamUpadhyayInBlue** [DataDog/dd-trace-js#905] opened 2020-04-06 07:38 UTC
Hi @rochdev 
I want to club all suffix names with **apiProject**. 
Eg: 
**apiProject-tcp**, **apiProject-mongodb** should not be listed as a separate service. It should be clubbed with apiProject. How can I do it in nodejs?

When I am viewing my traces using **dd-trace**, it shows multiple services like:

1. apiProject-mongodb
2. apiProject-tcp
3. apiProject-redis
4. apiProject-http-client
5. apiProject

Its consuming a lot of traces quota and hardly leaving any quota for my other projects. I want to keep only last 5th one (**i.e. apiProject**).

I tried this and it was successful to remove one service:

```
const tracer = require('dd-trace');
tracer.use('redis', {
  service: 'apiProject'
});
```

However, when I tried for multiple services I am not able to remove service name with additional suffix such as **mongodb, tcp, redis, http-client**.

Could you please help me?

**Comment by rochdev** [comment] 2020-04-06 14:54
Duplicate of #826

**Closed by rochdev** 2020-04-06 14:54 UTC
Labels: community, question
