### ISSUE TITLE
http-client doesn't receive any data since Node is updated

### ISSUE THREAD

**Issue by ZivojnovicZarko** [DataDog/dd-trace-js#2707] opened 2023-01-19 14:44 UTC
**Expected behaviour**
dd-trace should send data to datadog http-client service

**Actual behaviour**
http-client service is missing data

**Environment**

* **Node.js version:** 18.12.1
* **Tracer version:** 3.11.0
* **Relevant library versions:** Next.js 12.3.1

After updating Node to v.18 on our Next.js project datadog stopped receiving http-client data. On other Node.js project not using Next everything work fine, so our assumption is that something is wrong with combination Next.js / Node 18.
When downgrade Node to version 16.17.0 http-client service is back.

Any idea what should be the issue?

**Comment by tlhunter** [comment] 2023-02-10 20:02
Can you provide a minimal reproduction? Something that I can easily run locally that exhibits this issue? Once I have that I should be able to diagnose.

**Comment by rochdev** [comment] 2023-03-24 19:05
@ZivojnovicZarko Is this still an issue for you? And if it is, can you provide a reproduction snippet or steps to reproduce?

**Comment by mb21** [comment] 2023-04-04 07:51
I'm working with @ZivojnovicZarko and yes, unfortunately it's still an issue for us. Sorry that we haven't gotten around to setting up a reproducible example yet, but the theory is that setting up a new Next.js project and running it on Node.js (with the specified versions), and then making a `fetch` request (using the built-in fetch of node.js 18.12) from next's `getInitialProps` (or [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props)) will fail to generate an http-client trace.

**Comment by Qard** [comment] 2023-04-06 20:46
The fetch API is not yet supported. It's not built on http.Client so you won't get http-client spans from it.

**Comment by Qard** [comment] 2023-04-12 17:55
Do you mean global `fetch` function or `node-fetch`? Also, Next.js has it's own custom patched version of fetch, if I recall correctly, so we'd need specific support for that, as far I can tell.

**Comment by mb21** [comment] 2023-04-13 07:07
I'm saying that global `fetch` in node 18.12.1 works for us (not using node-fetch, which also used to work before we removed it).

> Next.js has it's own custom patched version of fetch, if I recall correctly, so we'd need specific support for that, as far I can tell.

I see, that's what we were suspecting and what this issue is about then. Weird thing is that the patched version of fetch worked as well on node 16.17.0. (Note: we're using next 12, not next 13 which has the new app directory, RSC and even more patched fetch.)

**Comment by mb21** [comment] 2023-04-13 07:12
Although interesting, `console.log(fetch.toString())` in an empty node prompt and in a next.js getInitialProps function both print the same thing:

```
async function fetch(input, init = undefined) {
    emitExperimentalWarning('The Fetch API');
    return lazyUndici().fetch(input, init);
  }
```

so not sure our theory is actually correct...

**Comment by tlhunter** [comment] 2023-12-18 22:55
It looks like this issue became a feature request for undici/fetch support. I'll close it as a duplicate of #1615 for now.

**Closed by tlhunter** 2023-12-18 22:55 UTC
Labels: bug, integration-fetch
