### ISSUE TITLE
ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/credentials'

### ISSUE THREAD

**Issue by marcingrabda** [DataDog/dd-trace-js#1156] opened 2020-11-12 20:51 UTC
**Describe the bug**
I see a lot of log statements that look like this:
```
ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/credentials'
```
This is what I added at the top of my lambda:
```
require('dd-trace').init();
```

**Environment**
AWS Lambda

* **Operation system:**
Amazon Linux
* **Node version:**
12
* **Tracer version:**
0.27.0
* **Agent version:**

**Comment by rochdev** [comment] 2020-11-13 01:26
> I see a lot of log statements that look like this

When you see log statements, do you mean actual log output (for example the console) or metadata in your traces?

**Comment by marcingrabda** [comment] 2020-12-23 05:02
It's actually in the metadata. Is there a way to get rid of it anyways?

**Comment by rochdev** [comment] 2021-04-23 18:14
Closing since this was resolved by making internal error metadata optional with the `internalErrors` option which defaults to false. Please feel free to reopen if you are still seeing this error with the latest version.

**Comment by siuying** [comment] 2022-04-25 22:08
I'm new to this library, but I regularly see these messages in my server log. I disabled fs plug-in to remove these errors for now.

**Comment by optikalefx** [comment] 2022-05-21 18:13
@rochdev this should be re-opened. There is no documented way https://datadoghq.dev/dd-trace-js/#tracer-settings to turn these errors off. I haven't figured out. I get many hundreds of these errors per hour flooding my logs.

**Comment by rochdev** [comment] 2022-05-26 00:31
@optikalefx That's because these errors should now always be off and there shouldn't be a way to turn them on. Did you notice the errors coming back in a specific version?

**Comment by diogenes-deliverr** [comment] 2022-05-28 08:53
Having the same error on an Elastic Beanstalk application: I didn't do any special configuration 

```
Error: ENOENT: no such file or directory, open '/root/.aws/config'
    at Object.openSync (fs.js:498:3)
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/tracer.js:97:56
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/tracer.js:44:56
    at Scope.activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope.js:29:14)
    at DatadogTracer.trace (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/tracer.js:44:35)
    at Object.openSync (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/tracer.js:97:23)
    at Object.readFileSync (fs.js:394:35)
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/tracer.js:97:56
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/tracer.js:44:56
    at Scope.activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope.js:29:14)
    at DatadogTracer.trace (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/tracer.js:44:35)
    at Object.readFileSync (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/tracer.js:97:23)
    at Object.readFileSync (/usr/src/app/node_modules/aws-sdk/lib/util.js:95:26)
    at IniLoader.parseFile (/usr/src/app/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:47)
    at IniLoader.loadFrom (/usr/src/app/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at resolveEndpointDiscoveryConfig (/usr/src/app/node_modules/aws-sdk/lib/discover_endpoint.js:299:58)
```

**Comment by rochdev** [comment] 2022-06-01 22:20
I tried to reproduce the issue but it works as expected for me. I do see the span trying to load the file, but it's not an error which is expected as we no longer capture `fs` errors. Can someone provide a reproduction snippet? Please also make sure to be on the latest version of the tracer to avoid the possibility of hitting a but that would already be fixed.

**Comment by rochdev** [comment] 2022-07-18 18:09
Closing as we have removed the `fs` integration starting when 3.0 lands, and it was the integration capturing this error. More context about this removal will be in the release notes for 3.0.

**Closed by rochdev** 2022-07-18 18:09 UTC
Labels: bug, community, integrations
