### ISSUE TITLE
Fastify does not reply to any http call

### ISSUE THREAD

**Issue by Eomm** [DataDog/dd-trace-js#2053] opened 2022-05-12 16:00 UTC
**Expected behaviour**
My Fastify server should works

**Actual behaviour**

The HTTP response is never sent back to the client
No errors
No logs except the Fastify’s incoming request line

**Steps to reproduce**

I was not able to reproduce the error locally.

The actual setup should be like the following:

```
process.env.DD_SERVICE = 'foo'
process.env.DD_LOGS_INJECTION = 'true'
process.env.DD_TRACE_ENABLED = 'true'
process.env.DD_PROFILING_ENABLED = 'false'
process.env.DD_ENABLED = 'true'
process.env.DD_ENV = 'local'

const tracer = require('dd-trace').init({
  logInjection: true,
  sampleRate: 1,
})
tracer.use('fastify', {
  analytics: true,
  blocklist: ['/alive'],
})

const fastify = require('fastify')({
  logger: true,
})
fastify.get('/', (request, reply) => {
  reply.send({ hello: 'world' })
})
fastify.listen(8080)
```

**Environment**

* **Operation system:**
Linux (docker image from nodejs-alpine)

* **Node.js version:**
16.x

* **Tracer version:**
v2.7.0

* **Agent version:**
v7.32.4

* **Relevant library versions:**
`dd-trace` v2.6.0 works ✅
`dd-trace` v2.7.0 does not work 💔
`fastify` v3.29.0

**Comment by bengl** [comment] 2022-05-12 19:18
Hi @Eomm! Thanks for reporting!

I was also not able to reproduce locally. However, the error sounds a lot like #2047, which is now fixed on master and the fix should be included in our next patch release (today or tomorrow). If you're able to deploy from master, I'd suggest trying that for now to see if that resolves it for you.

**Closed as completed** 2022-05-16 13:56 UTC
Labels: bug
