### ISSUE TITLE
Trace not being  sent to datadog when  express endpoint uses schema-link

### ISSUE THREAD

**Issue by guilherme** [DataDog/dd-trace-js#709] opened 2019-10-09 05:46 UTC
**Describe the bug**

I am having an issue when express and graphql plugins are combined. My situation is the following: 
whenever I try to do a request on a route that uses apollo's  [SchemaLink](https://www.apollographql.com/docs/link/links/schema/) to make GraphQL queries the tracing doesn't get reported to Datadog. 

If I hit an endpoint that only hits the GraphQL or if I hit an endpoint that doesn't have graphql it also works but when it has both (schema link case) it doesn't work.

I did some debugging and I found that a bunch of traces don't finish in this scenario (by looking at the SpanProcessor: traces.started and traces.finished).

And if I replace the schema link with [HttpLink](https://www.apollographql.com/docs/link/links/http/)  which means another http request is sent, then it works fine. 

Does anyone have any idea why would that happen?

**Environment**
* **Operation system:**
OSX 
* **Node version:**
node v8.15.0
* **Tracer version:**
0.15.3

* **Agent version:**
docker latest.

**Comment by rochdev** [comment] 2019-10-10 10:00
> I am having an issue when express and graphql plugins are combined.

Just to confirm, it works even with a SchemaLink but only if the `express` plugin is not enabled?

> I did some debugging and I found that a bunch of traces don't finish in this scenario (by looking at the SpanProcessor: traces.started and traces.finished).

What is the value of `span._spanContext._name` for entries that are in `traces.started` but not `traces.finished` for traces that never finish? This will give me an idea of which span is causing the issue.

**Comment by guilherme** [comment] 2019-10-10 10:40
Hi @rochdev, thanks for answering. I was able to identify the issue and fix it.


Here's what I think it happened:

My SchemaLink had `context` as static object and there were multiple query calls, therefore, multiple execute calls. After debugging I found that the `finish` and `finishResolvers` was only called once. [See](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-graphql/src/index.js#L38)
dd-trace mutates the `context` when performing execution and sets a `_datadog_graphql`. because this was shared across the multiple requests and there's a [guard](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-graphql/src/index.js#L21) in there that prevents setting up traces.Somehow It got in the way.

After I changed the context to a function it resolved the issue.

Previously the code was:
``` 
    const apolloClient = createApolloClient({
      ssrMode: true,
      link: new SchemaLink({
        schema: executableSchema,
        context: {
          ...graphQLContext,
          requestId: uuid(),
          requestId,
          req: request,
          loader: dataloaderFactory(),
          loader: dataLoader,
          res: response,
        },
        }),
      }),
    }, null, { ssrQueryParams: attributesFromQuery(request.query) });
```

Then changed to:

``` 
    const apolloClient = createApolloClient({
      ssrMode: true,
      link: new SchemaLink({
        schema: executableSchema,
        context: () => ({
          ...graphQLContext,
          requestId: uuid(),
          requestId,
          req: request,
          loader: dataloaderFactory(),
          loader: dataLoader,
          res: response,
        }),
        },
      }),
    }, null, { ssrQueryParams: attributesFromQuery(request.query) });
```

It worked.


> Just to confirm, it works even with a SchemaLink but only if the express plugin is not enabled?
no, they both are enabled.


> What is the value of `span._spanContext._name` for entries that are in `traces.started` but not `traces.finished` for traces that never finish? This will give me an idea of which span is causing the issue.

Most of them were graphQL field resolvers.

**Comment by guilherme** [comment] 2019-10-10 11:31
This test here:

```it('should support multiple executions with the same contextValue')```

seem to not be calling the finish  twice.

**Comment by rochdev** [comment] 2019-10-11 13:55
Glad you could get it to work! Since `context` is meant to be shared across a specific request and not globally, this is the expected behavior. I don't understand why Apollo allows configuring a global context to be reused across all requests since that doesn't really make sense, but since they do, this is definitely something we should handle. This is quite a big change since this means rewriting the logic to not rely on the context at all. I'll leave this issue opened to make sure we eventually get to it and for anyone else who gets the same issue.

**Comment by rochdev** [comment] 2019-10-11 13:57
> Shouldn't calling finish twice be part of the expectation of this test?

This test is mostly to ensure that there is no conflict that could cause an error, and in the context of a single request. While related, it's not exactly the same issue as described above. This is something we'll eventually test once the implementation supports this use case.

**Comment by bengl** [comment] 2022-01-11 20:38
This issue seems resolved (and is several years old), so I'm closing it. Please feel free to comment or re-open if the need arises, or if you think it wasn't resolved.

**Closed by bengl** 2022-01-11 20:38 UTC
Labels: bug, community, integrations
