### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by mbjurman** [DataDog/dd-trace-js#2628] opened 2022-12-20 07:43 UTC
Updating from dd-trace 3.9.0 to 3.9.3, we noticed significant increased memory usage over time on our service. Reverting to 3.9.0 resolved the issue.

We had 3.9.3 live for about three days and as you can see in this image the memory usage had a classic memory leak pattern those days:

![image](https://user-images.githubusercontent.com/1282945/208609343-041b21c6-01ec-4f33-b38b-4dc02b05d877.png)

**Environment**

* **Operation system:** docker image `FROM node:16.18.1-bullseye-slim AS base`
* **Node.js version:** 16.18.1
* **Tracer version:** 3.9.3
* **Agent version:** datadog/agent:7.40.1
* **Relevant library versions:**
  - koa@2.14.1
  - bunyan@1.8.15

**Comment by rburgst** [comment] 2022-12-20 11:38
same here, we are using fastify, pino and rolled back to 3.8.0, now the leak is gone.

**Comment by chin2km** [comment] 2022-12-20 13:16
same here. upgraded from 3.6.0 to 3.9.3 to run into this issue. Reverting to 3.6.0 fixes the issue.

**Comment by Qard** [comment] 2022-12-22 04:12
I suspect this is related to the issue fixed by this PR: https://github.com/DataDog/dd-trace-js/pull/2633

That should hopefully get into a new release soon so keep an eye our for that. 😄

**Comment by marcghorayeb** [comment] 2023-01-06 00:43
We can confirm a memory leak on 3.9.3. We downgraded to 3.6.0 as that was the one we had previously and the excessive memory usage resolved itself.
Our stack has fastify, pino and graphql.

**Comment by jgrumboe** [comment] 2023-01-08 15:32
@rburgst version 3.10.0 is out which includes the http state restore fix #2633.
Could be worth a try.

Although it doesn't include #2641, which could also have an impact.

**Comment by rburgst** [comment] 2023-01-10 14:32
@jgrumboe tried 3.10.0 and so far (since the last 4h) this looks better, I cannot see the mem leak so far.

**Comment by mbjurman** [comment] 2023-01-12 08:04
@Qard We rolled out 3.10.0 yesterday and yes it looks like it's fixed :+1:

**Comment by jgrumboe** [comment] 2023-01-12 09:19
I saw that 3.11.0 is out since yesterday, which also includes the router state fix.

**Comment by Qard** [comment] 2023-01-12 20:24
@chin2km @marcghorayeb Is the leak resolved in the latest release for you too? Just want to make sure everyone's issue is fixed before I close this.

**Comment by marcghorayeb** [comment] 2023-01-14 00:19
Will deploy in the coming days and report back here, thanks for the update 👍

**Comment by laudibert** [comment] 2023-01-18 07:48
3.11.0 deployed here and memory leak is still there.

It seems directly related to HTTP requests, a health checkup route that just returns `true` is being called every second. Other than that, no activity happens on that application.

**Stack**

- Node.js version: 16.14.2
- Agent version: 7.40.0
- Relevant library versions:
  - @nestjs/common@9.2.0
  - express@4.18.2

**Comment by Qard** [comment] 2023-01-18 23:06
@laudibert do you have a reduced reproduction case? Looks like you're using nest, which we don't currently support, so could be nest is doing something weird. I'd recommend opening a new issue with more details so we can focus specifically on your issue.

**Comment by torasmu** [comment] 2023-02-22 19:19
FYI for others - We just addressed a memory leak in an express server with fairly high POST traffic by upgrading from `3.9.3` to `3.14.1`. We couldn't replicate locally because we don't have dd-trace on local. We did a heap dump with `v8.getHeapSnapshot()` in production and found many request bodies were being leaked and were tied together by `DatadogSpan` and `DatadogSpanContext`.

**Comment by Qard** [comment] 2023-02-22 23:22
Yes, that's a known and fixed leak. As far as I can tell everyone in the thread that ran into that has had their issue resolved. The nestjs leak is likely something else thus my asking for a new issue to track that.

**Comment by tlhunter** [comment] 2023-12-18 19:15
I'm going to close this issue as it's pretty old and OP @mbjurman seems to have their original problem solved.

**Closed by tlhunter** 2023-12-18 19:15 UTC
Labels: bug
