### ISSUE TITLE
Blacklist http option conflicting with .init() variables

### ISSUE THREAD

**Issue by imjustabee** [DataDog/dd-trace-js#1087] opened 2020-09-15 18:07 UTC
I am trying to utilize the blacklist option within. the http plugin, but I keep seeing those urls getting traced. I'm curious if this is coming from the fact that I'm calling the key values logInjection and analytics from within the .init() option. I have a requirement to leave these values within the init, so I'm curious of a work-around if this is the case.

```
tracer.init({
    env: dev,
    hostname: <HOSTNAME>,
    logInjection: true
    analytics: true,
  });
  tracer.use('http', {
    blacklist: ['/__healthcheck', '/__documentation']
  });
```

**Comment by rochdev** [comment] 2020-09-15 18:10
Usually, this happens because the module is loaded before the tracer. The tracer must be initialized before all instrumented modules, otherwise it may result in unexpected behaviours, the most common one being the plugin configuration not working. Could you share the top of your entry point, and whether you use a bundler like Webpack?

**Comment by imjustabee** [comment] 2020-09-15 18:15
```
require('dotenv').config();

const definitions = require('./definitions');
const tracer = require('dd-trace');
if (definitions.tracerReq) {
tracer.init({
    env: dev,
    hostname: <HOSTNAME>,
    logInjection: true
    analytics: true,
  });
  tracer.use('http', {
    blacklist: ['/__healthcheck', '/__documentation']
  });
}
```

And this is not using webpack, but it is using hapi in a few private custom npm modules

**Comment by rochdev** [comment] 2020-09-16 17:38
What's in `./definitions`? Anything that could be using `http`? Also, are you using a framework or `http` directly? If using a framework the blacklist should be on the plugin for the framework and not on `http`.

**Comment by rochdev** [comment] 2020-10-07 00:56
@imjustabee Are you still having this issue?

**Comment by rochdev** [comment] 2020-11-03 18:14
Closing as this is very likely due to load order issue. Ensuring `tracer.init` happens before anything else is required for everything to work properly. One way to guarantee this is to initialize the tracer directly from the CLI like so `node --require 'dd-trace/init' ./index.js`.

**Closed by rochdev** 2020-11-03 18:14 UTC
Labels: community, integrations, question

**Comment by imjustabee** [comment] 2021-02-02 22:26
@rochdev apologies for the late reply. While in some of my micro-services this is not an issue, I do keep finding it reoccurring in others. Even with your suggested fix, the blocklist option keeps being ignored for the http plugin. This does not seems to any sort of load order issue, as init is most certainly called before everything else

**Comment by imjustabee** [comment] 2021-02-02 22:27
> What's in `./definitions`? Anything that could be using `http`? Also, are you using a framework or `http` directly? If using a framework the blacklist should be on the plugin for the framework and not on `http`.

defs files is merely a list of variables, and this is using pure http
