### ISSUE TITLE
Express HTTP span headers are null

### ISSUE THREAD

**Issue by dhay** [DataDog/dd-trace-js#1333] opened 2021-04-26 22:37 UTC
**Describe the bug**
I'm still seeing the behavior described in https://github.com/DataDog/dd-trace-js/issues/395

We've tried configuring dd-trace as follows:
```
const tracer = require('dd-trace');
const express = require('express');

tracer.init({enabled: true});
tracer.use('express', {
  headers: ['user-agent', 'x-forwarded-for']
});


const app = express();
const port = 3333;

app.get('/', (req, res) => res.send('Hello World!'))
app.listen(port, () => console.log(`Ready for requests`))
```
However, when I hook up the debugger, `createWrapHandle` is called as a result of our call to `tracer.init` and never again.  When the call to `addHeaders` is called, `req._datadog.config.headers` is null/undefined.  

It seems to me that when I call `tracer.use`, it captures the config, but somehow the plugin isn't properly re-initialized...in particular, the express `handle` call is not re-patched.  I've tried tracing through the code with the debugger to see where things go wrong, but I haven't been able to figure out what's missing.  The new configuration is properly captured in the plugin configuration, but not propagated to the wrapper.

**Environment**

* **Operation system:** MacOS Mojave (10.14.6)
* **Node version:** 14.15.0
* **Tracer version:** 0.32.2
* **Express version:** 4.17.1

**Comment by rochdev** [comment] 2021-04-27 01:31
Closing as a duplicate of #395, but since the description in this issue is more complete I will answer here as well. The tracer _must_ be initialized before any other module is imported, which is not the case in your snippet. Basically it should be instead:

```js
const tracer = require('dd-trace');

tracer.init({enabled: true});
tracer.use('express', {
  headers: ['user-agent', 'x-forwarded-for']
});

const express = require('express');
```

Please feel free to reopen if moving the tracer initialization to the very top of your application entry point doesn't solve the issue.

**Closed by rochdev** 2021-04-27 01:31 UTC
Labels: bug

**Comment by rochdev** [comment] 2021-04-27 01:34
> The new configuration is properly captured in the plugin configuration, but not propagated to the wrapper.

This is also something we are working on right now so that in the future the tracer will be more resilient to when it is initialized and configured, but it will likely only be in a few months as there are many changes that need to happen in the tracer to enable that.

**Comment by dhay** [comment] 2021-04-27 13:49
Perfect!  Thanks for the help!  Somehow I missed the importance of executing the call to `init()` prior to importing/requiring additional modules...though it's pretty clear from your examples.
