### ISSUE TITLE
APM service name not set consistently

### ISSUE THREAD

**Issue by esselius** [DataDog/dd-trace-js#152] opened 2018-06-18 12:15 UTC
The express and http plugins (possible more) do not set the service name tag in the same way, see:

https://github.com/DataDog/dd-trace-js/blob/28049d943624545c4f42f4641163e6104dd85b83/src/plugins/express.js#L35

https://github.com/DataDog/dd-trace-js/blob/28049d943624545c4f42f4641163e6104dd85b83/src/plugins/http.js#L39

This made my service show up as both `*service-name*` + `http-client`.

I set service name through:
```
require('dd-trace').init({
  service: process.env.SERVICE_NAME,
});
```

**Comment by rochdev** [comment] 2018-06-18 15:06
This is actually by design. Basically when calling remote services or data stores, the name of the remote service is used instead of the name of the current service. The service name will be the name of the current service only when it's on the server side of the operation and not on the client side.

I do agree however that for outbound HTTP calls it can be limited at the moment since `http-client` doesn't mean much. We are currently working on a better design for HTTP.

@esselius Did you find this behavior confusing? What would you expect the service name to be in the following cases for example:

* A request to the current service, for example an express server (currently the name of the service or fallback to module name)
* An outbound request to a users service at `http://users.example.com/api` (currently `http-client`)
* A query to a data store, such as MongoDB (currently `mongodb`)

All of these can be configured on the plugins as well, but limited to a single service name per plugin at the moment.

**Comment by esselius** [comment] 2018-06-19 12:29
So I did some adjustments to make it work more like I expect:
```
const tracer = require('dd-trace').init({
  env: process.env.ENVIRONMENT_TYPE,
});

tracer.use('http', {
  service: process.env.DD_SERVICE_NAME,
});

tracer.use('https', {
  service: process.env.DD_SERVICE_NAME,
});
```

This now looks like this in APM:
![screen shot 2018-06-19 at 14 07 19](https://user-images.githubusercontent.com/1178200/41596342-57fc72d4-73ca-11e8-8670-db836b8a624f.png)

The service in question (sluss-router) is a reverse-proxy implemented in node (using `http-proxy-middleware`), in the screenshot proxying a request for the service `ebok-sl`.

In this scenario it's kinda confusing to have the request be it's own service, when the upstream service is already available in APM.

**Comment by dbsanfte** [comment] 2018-06-19 12:37
We just set up APM last week, and we also find this dual behaviour to be confusing, as it results in strange looking flame graphs that just confuse us:

![image](https://user-images.githubusercontent.com/3513358/41597616-d4066484-73c5-11e8-8a8d-b0cfd4f6aa7b.png)

I like the graph that @esselius has managed to generate a lot better.

**Comment by rochdev** [comment] 2018-06-19 15:40
@dbsanfte Does configuring the tracer and/or plugins as @esselius mentioned work for your use case as well? We can review the current defaults, but the important part for now I think is that it's flexible enough to allow configuring this in a way that makes sense for any use case.

**Comment by rochdev** [comment] 2018-06-19 19:05
Would scoping them to the service help? For example `service-1`, `service-1-http-client` and `service-1-redis`?

**Comment by dbsanfte** [comment] 2018-06-20 11:31
Hi @rochdev ,

Yes, scoping them would be fine with us. 

I will implement @esselius solution for now and evaluate it for our use case.

**Comment by rochdev** [comment] 2018-08-15 15:36
The service names have been updated according to this discussion.

In summary:

* Web servers use the global service name from the tracer (i.e. `auth`)
* Other integrations use the name of instrumentation, prefixed with the global service name (i.e. `auth-redis`)
* The `http` plugin specifically can be configured using the `splitByDomain` option which will instead use the remote endpoint as the service name (i.e. `sub.domain.com`)
* In all cases this is configurable on every plugin by using the `service` option.

I'll close this for now but feel free to reopen if you feel the new behavior is still incorrect.

**Closed by rochdev** 2018-08-15 15:36 UTC

**Comment by esselius** [comment] 2018-08-16 06:56
Looks like a great solutions, thank you for your work @rochdev!

**Comment by prazzusa** [comment] 2019-04-05 18:44
I am having the similar issue I think. I am pushing my nodejs application to DataDog and it is appending http-client to my service name which I don't want. This workaround did not help. Please suggest. 
const tracer = require('dd-trace').init({
  service: process.env.DD_SERVICE_NAME
})
where DD_SERVICE_NAME refers to the service name. But DataDog APM Service is showing service name + http-client

**Comment by rochdev** [comment] 2019-04-05 18:53
@prazzusa Any client integration will append the name of the integration by default. You can override this behavior on a per-service basis.

For example:

```js
tracer.use('http', {
  service: 'my-service'
})
```
