### ISSUE TITLE
Span name from express always reported as anonymous in dashboard

### ISSUE THREAD

**Issue by samjacoby** [DataDog/dd-trace-js#908] opened 2020-04-08 17:13 UTC
The custom span example, here, https://docs.datadoghq.com/tracing/guide/adding_metadata_to_spans/?tab=nodejs, doesn't seem work as expected. In my flamegraph, it always reads as `anonymous`, rather than the assigned name.

My snippet (below) is somewhat modified, so maybe I've introduced an error:
```javascript
app.get('/my-test', function(req, res, next) {
  const span = tracer.startSpan('web.request')

  span.setTag('http.url', req.url)
  span.addTags({'http.method': req.method})
  span.addTags({'foo': 'bar'})

  res.render('index', { title: 'Test' });
});
```
I'd expect to see a trace called `web.request`. Instead, it appears as "anonymous". 

![image](https://user-images.githubusercontent.com/410825/78720586-f7eb4b00-78f3-11ea-9a5b-6fa057915e3f.png)

Not sure if I'm just making a simple mistake here; have tried a number of permutations, always with this result. Would appreciate any guidance! 

**Environment**
OSX
* **Operation system:**
* **Node version:**
v10.19.0
* **Tracer version:**
^0.19.0
* **Agent version:**
Version: 7.18.0

**Comment by rochdev** [comment] 2020-04-09 23:49
The span you are seeing as `<anonymous>` is actually a span created by our `express` integration and not the span from your snippet. The example you are referring to is for manual tracing with no auto-instrumentation at all, which is not the case in your example.

Since I'm not sure of your use case, I'll provide an answer for each potential one.

#### web.request as child of express.middleware

If you want your `web.request` span to be a child of our `express.middleware` span, it should explicitly set the parent using `span.startSpan('web.request', { childOf: tracer.scope().active() })`. You also have to make sure to finish the span after, otherwise it will prevent the trace from finishing and tracing will stop working completely. Handling the resource name and errors would also need to be done manually.

For example:

```js
app.get('/my-test', function(req, res, next) {
  const childOf = tracer.scope().active()
  const span = tracer.startSpan('web.request', { childOf })

  span.setTag('resource.name', 'your-resource-name') // this is what will be shown in the UI beside the span name
  span.setTag('http.url', req.url)
  span.addTags({'http.method': req.method})
  span.addTags({'foo': 'bar'})

  res.render('index', { title: 'Test' });

  // call span.setTag('error', err) in case of an error in the operation
  // call span.finish() when the operation is finished (after render?)
});
```

Alternatively, depending on your use case, there is a new and simpler API you can use that handles all of this for you. This is currently documented in a [PR](https://github.com/DataDog/dd-trace-js/blob/ae833b8ce0a45aa852e42c6cbf536f1b0814ba85/docs/API.md#manual-instrumentation) if you want to take a look (links won't work because it depends on the complete generated doc).

#### Manual instrumentation

If you are trying to do manual instrumentation without any automatic instrumentation so that your `web.request` is the root span, then you would have to disable our integrations. We strongly recommend against that, but if this is your use case please let me know and I'll provide more guidance how to do it.

#### Instrument the middleware

If what you are trying to do is instrumenting the request and/or middleware/handler, this is already done out of the box and you don't need an additional span.

#### Alter the metadata

If your use case is to alter the metadata of the current trace (i.e. the URL) then you don't need to create an additional span for that. In that case you can simply use span hooks to update the URL with the correct value.

For example:

```js
// right after tracer.init() at the top of the application entrypoint
tracer.use('express', {
  hooks: {
    request (span, req, res) {
      span.setTag('foo', req.foo)
    }
  }
})
```

Please let me know if I covered your use case!

**Comment by samjacoby** [comment] 2020-04-15 15:18
Thank you — this has been enormously helpful. Using `tracer.trace` and tracer.wrap`, I've been able to get some very good flamegraphs. 

I still have some questions about reducing the cardinality of my requests — we have some pattern matchers in our express routes that behave wonkily, where `myMatchRouter` does a bunch of custom stuff.
```javascript
server.use(argv.path, myMatchRouter(myRegex, function (request, response, raw, repository, branch, revision, file, next) {
  // do work
  return res.end()
}
```
I can get the full path by adding a hook like so:
```javascript
tracer.use('express', {
  hooks: {
    request: (span, req, res) => {
      span.setTag('http.route', req.originalUrl) 
    }
  }
})
```
But that actually gives me _too_ much cardinality — I'd like to be able to group by certain characteristics, like basepath, while still preserving the full URL. I think I can probably do that by just by customizing the hook.

Anyhow, thank you for the assist!

**Comment by rochdev** [comment] 2020-04-16 18:10
One thing you could do is to set the route that was matched on the request, for example `req.route = matchedRegex.toString()` and then use that in the hook to set the `http.route` tag.

**Comment by jpike88** [comment] 2020-06-22 10:04
Related: I'm having trouble getting more detail out of my flame graphs.

I have code like this
```
await tracer.trace(fullFunctionName, async () => {
	const data = await apiFunction.execute();
	return data;
})
```

Which changes my flame graph only slightly, to this (see highlighted name on the right):

<img width="944" alt="Screen Shot 2020-06-22 at 6 04 06 PM" src="https://user-images.githubusercontent.com/9585787/85275339-c6c1f600-b4b2-11ea-969a-3d305118bd3f.png">

I expected a more detailed graph, so I can see what child functions are getting called?

**Comment by rochdev** [comment] 2020-06-22 16:36
@jpike88 `trace.trace()` creates a span in the trace and manages its lifecycle, which is the behavior seen in the screenshot. Could you describe in more details what was the expected behavior?

**Comment by jpike88** [comment] 2020-06-22 19:19
That function isn’t flat, it goes deeper into more async await calls.

There’s nothing between that function and the MySQL query below it, when it’s about three calls deeper before a sql query is invoked.

**Comment by rochdev** [comment] 2020-06-22 19:41
Calling `trace.trace()` creates a span directly and doesn't track further function calls. What is your use case for tracking every individual functions?

**Comment by jpike88** [comment] 2020-06-23 13:56
Well, traces aren't really traces if they don't show the full stack. I'm debugging a performance issue right now and all that span is telling me is that a particular API method is at fault, but not what child function is the culprit.

**Comment by rochdev** [comment] 2020-06-25 16:21
> Well, traces aren't really traces if they don't show the full stack.

What you are referring to is a stack trace. In the context of distributed tracing, the minimum number of spans for the trace is one per service since the idea is to find which service is slowing down the request. We go slightly beyond that and add spans for IO and a few internal operations, while also allowing custom instrumentation.

> I'm debugging a performance issue right now and all that span is telling me is that a particular API method is at fault, but not what child function is the culprit.

Does your issue happen only for a specific request or is it a more general issue? For a more general issue profiling would be better than tracing at showing which functions are the slowest in the service.

**Comment by superwesker1988** [comment] 2020-07-24 14:13
Hi just piggy back on this issue. Is there a way to have built-in middleware instrumentation reflecting the name of middleware instead of "anonymous" as shown by OP's screenshot? Is it something we could configure if the middleware imported does not export their function as a named function?

**Comment by rochdev** [comment] 2020-07-24 14:26
> Is there a way to have built-in middleware instrumentation reflecting the name of middleware instead of "anonymous" as shown by OP's screenshot?

Unfortunately this is not possible at the moment. Middleware should export a named function to make debugging and telemetry easier since the function name would be reflected in stack traces, profiles, traces, and so on.

A workaround would be to wrap the middleware in a named function so that the tracer is able to identify it.

> Is it something we could configure if the middleware imported does not export their function as a named function?

Do you have an API in mind of how to do the mapping?

**Comment by superwesker1988** [comment] 2020-07-24 14:58
Hi @rochdev , thanks so much for the suggestion! 

Just to be clear:
1. If a middleware is exported with named function, current 'dd-trace' should be able to log the name of middleware.
2. In case a middleware is not exported with named, we could wrap the middleware with our own named function as a workaround.

> Do you have an API in mind of how to do the mapping?
Did you mean a suggestion from me regarding an API to customize the mapping? If so, I'm not really sure ATM since I'm pretty new to dd-trace.  I can kinda imagine it would not be straightforward because you would need to provide certain information to users so that they could make the decision on their mapping while the information is very limited regarding the middleware. If point 2 works, it should be able to cover the majority of use-cases IMO.

**Comment by rochdev** [comment] 2020-07-24 15:17
> In case a middleware is not exported with named, we could wrap the middleware with our own named function as a workaround.

Correct, and then the tracer will use that. The only important thing to keep in mind is that the wrapper must have the same signature as the original middleware since Express uses the length of the function to make decisions on how to call it.

**Comment by andrewsouthard1** [comment] 2020-09-23 18:50
If anyone is still having issues here, please let us know. Otherwise closing out.

**Closed by andrewsouthard1** 2020-09-23 18:50 UTC
Labels: community, question
