### ISSUE TITLE
Plugin Service names do not work for all plugins anymore

### ISSUE THREAD

**Issue by bvandermeersch** [DataDog/dd-trace-js#1742] opened 2022-01-07 02:08 UTC
**Describe the bug**
We recently updated from 0.x to 1.6 of the dd-trace nodejs library. Our api also has graphql in it.
on version 0.x it auto named all graphql stuff as api-graphql and api stuff as api.

Now on 1.x the graphql service if now combined with api under the api serivce.

However api-redis and api-mysql are still named appropriately.

**Environment**

* **Operation system:**
* fargate ecs
* **Node version:**
*  12
* **Tracer version:**
* 1.6
* **Agent version:**
* latest

New 1.6 service layout
![Screenshot from 2022-01-06 19-41-38](https://user-images.githubusercontent.com/16663002/148479824-58c02212-85ae-476f-b77c-a5cd0c4c28a9.png)

Old 0.x service layout
![Screenshot from 2022-01-06 19-39-11](https://user-images.githubusercontent.com/16663002/148479825-23d123da-2bb1-41d3-9b19-360b765782fb.png)

How do i get it back to how it was? Our only change was updating the version.

**Comment by rochdev** [comment] 2022-01-10 18:30
Closing as it is a duplicate of #1679 with a workaround provided in https://github.com/DataDog/dd-trace-js/issues/1679#issuecomment-966533530.

**Closed by rochdev** 2022-01-10 18:30 UTC
Labels: bug
