### ISSUE TITLE
dd-trace causes crash on startup with meteor app + node 14.

### ISSUE THREAD

**Issue by perbergland** [DataDog/dd-trace-js#1384] opened 2021-05-26 18:32 UTC
**Describe the bug**

Upon startup of a meteor application, the app crashes.
This is with Meteor 2.3 which is in beta and updates nodejs from v12 to v14.

**Environment**

* **Operating system:**
macos 11.3.1
* **Node version:**
14.17.0
* **Tracer version:**
0.31.4

I’m aware of https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/nodejs/#fibers but in case this is fixable it would be nice if it could be fixed.

The same code worked with node v12.22.1

Stack trace:

TypeError: Cannot read property 'Symbol(ddResourceStore)' of undefined
    at Scope._init (/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js:70:33)
    at emitInitNative (internal/async_hooks.js:207:43)
    at emitInitScript (internal/async_hooks.js:475:3)
    at process.nextTick (internal/process/task_queues.js:133:5)
    at ConnectionPool.checkIn (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection_pool.js:261:13)
    at .meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection_pool.js:355:16
    at handleOperationResult (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:376:20)
    at MessageStream.emit (domain.js:470:12)
    at processIncomingData (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:745:22)
    at Socket.emit (events.js:376:20)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
TypeError: Cannot read property 'Symbol(ddResourceStore)' of undefined
    at Scope._init (/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js:70:33)
    at emitInitNative (internal/async_hooks.js:207:43)
    at emitInitScript (internal/async_hooks.js:475:3)
    at trackPromise (internal/async_hooks.js:317:5)
    at fastPromiseHook (internal/async_hooks.js:327:7)
    at Function.reject (<anonymous>)
    at process.<anonymous> (packages/inter-process-messaging.js:227:47)
    at process.emit (events.js:376:20)
    at process.emit (domain.js:470:12)
    at process.exit (internal/process/per_thread.js:169:15)
    at fatalError (internal/async_hooks.js:180:11)
    at emitInitNative (internal/async_hooks.js:214:5)
    at emitInitScript (internal/async_hooks.js:475:3)
    at process.nextTick (internal/process/task_queues.js:133:5)
    at ConnectionPool.checkIn (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection_pool.js:261:13)
    at .meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection_pool.js:355:16
    at handleOperationResult (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:376:20)
    at MessageStream.emit (domain.js:470:12)
    at processIncomingData (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (.meteor/packages/npm-mongo/.3.9.0.1pn50m2.1qtu++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:42:5)

**Comment by rochdev** [comment] 2021-05-26 19:06
Unfortunately as you mentioned above Meteor applications are not supported by dd-trace, so the recommendation here would be to uninstall dd-trace from the application. We fixed a similar crash for Meteor 2.0, and we could try to fix this one too, but at the end of the day it could still randomly crash in a future version and cause all sorts of unexpected behaviours. This is because Fibers, and by extension Meteor, are fundamentally incompatible with quite a few built-in core modules of Node that are needed by APM vendors like us to function. Until Meteor is updated to remove its reliance on Fibers and use a different construct like async/await, dd-trace, or any APM tool for that matter, **should not** be used with Meteor.

**Comment by rochdev** [comment] 2021-05-28 17:20
The error should be fixed when #1390 lands. However, it's important that you still stop using dd-trace, and any module outside of the Meteor ecosystem, because Meteor is not compatible with the Node ecosystem and things might otherwise randomly break or misbehave. The Meteor team are working on this issue, but until it's fixed, this is the only way to safely use Meteor.

**Comment by perbergland** [comment] 2021-05-31 10:09
"Meteor is not compatible with the Node ecosystem" is a very harsh statement given how many people use various npm packages successfully with meteor.

The coroutines library [node-fibers](https://github.com/laverdet/node-fibers), however, recently (after many many years of being in service) became incompatible with improvements within nodejs and specifically for APM packages that rely on async-hooks.

Discussions around whether it’s possible to modify node-fibers to make it compatible with these changes are ongoing, as well as a huge and enormously impactful effort to start removing all coroutine (fibers) code from Meteor and migrate to async/await.

**Comment by bengl** [comment] 2021-06-28 14:38
@perbergland This was fixed in #1390, which landed in 0.34.1. Please feel free to comment, reopen or reach out to support if the latest `dd-trace` still causes a crash.

**Closed by bengl** 2021-06-28 14:38 UTC
Labels: integrations, question

**Comment by StephenKoller** [comment] 2021-07-13 16:35
>In the future, there will be a time when all packages will be migrated to npm, but currently there are benefits to both systems.

https://guide.meteor.com/atmosphere-vs-npm.html
