### ISSUE TITLE
memory leak observed since 2.11

### ISSUE THREAD

**Issue by amirbarkai** [DataDog/dd-trace-js#2640] opened 2022-12-25 12:24 UTC
**Expected behaviour**
we recently upgraded from an old dd-trace version 0.31, to the latest 3.9.3 (big jump).
Since the upgrade, we're experiencing a notable memory leak.
after some investigation, mainly applying binary search on the dd-trace version, we concluded that the leak starts in **version 2.11**. (2.10 is the last version that our benchmark didn't have the leak).
its happening in a much prominent way in pubsub's subscription heavy services.

the load testing & benchmark were made with the same script, for the same duration. 

**Actual behaviour**
no leak ?

**Environment**

* **Node.js version:** 16
* **Tracer version:** 3.9.3

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/97064295/209467683-ec39cd1c-42bc-4dad-bbf9-01aeacc4cab5.png">

**Comment by tlhunter** [comment] 2022-12-27 17:26
From the memory usage screenshot it looks like the memory growth is bounded, or in other words, the library consumes a flat increase in memory (approx 50MB) but that memory consumption doesn't continuously grow. Does that observation align with what you're seeing?

**Comment by amirbarkai** [comment] 2022-12-29 08:59
nope. that's not correct. its bounded just because the stress test ran for 15 minute each time, and it grow throughout that time. after the test ends, GC is performed, but not goes back to its original memory size, but rather reduced by 10-15% only. 
in our production, the fact that GC not clearing it overtime, causes OOM.
its a bit diffecult to see this in the image attached, because there are cases where we saw the increase, and we concluded straight away its a "leaked" version, and moved on to deploy a new version.

there was something in 2.11 that started to consume drastically more memory and not getting freed.

**Comment by tlhunter** [comment] 2022-12-30 17:53
Can you enable runtime metrics via `DD_RUNTIME_METRICS_ENABLED=true` and also enable tracking of any spans that might be leaking via `DD_TRACE_EXPERIMENTAL_SPAN_COUNTS=true`? With those enabled please share the resulting `runtime.node.spans.open` and `runtime.node.spans.open.by.name` metrics with me via email at my github username @ datadog.com.

With that information I should be able to deduce any non garbage collected metrics and which integration it's associated with.

If those metrics come back empty then I'll probably need a heapdump of your process before and after a benchmark. That's usually a little more involved to collect so the metrics are a fine first step.

**Comment by amirbarkai** [comment] 2023-01-01 06:33
Will do. Thanks

**Comment by floriantz** [comment] 2023-01-19 10:44
I can confirm there is an issue with memory usage after bumping up from the `2.9.1` version we were using. This is the RAM usage of our node.js app on a container with 4Gb memory:

<img width="693" alt="Screenshot 2023-01-19 at 11 03 43" src="https://user-images.githubusercontent.com/44224782/213421868-2d98aae6-d34b-48eb-bbc8-0e95799fe42d.png">

After bumping down the version, we went back to our usual pattern of hovering around 15% RAM usage.
It looked like the memory was very often freed during the night around midnight so we didn't get oom trouble but still.

**Comment by sjgupta19** [comment] 2023-03-20 22:50
We upgraded the dd-trace package from 2.10.0 to 2.23.0 and started seeing some spikes in the pubsub consumers. 
![image](https://user-images.githubusercontent.com/105396748/226482652-9672da75-8fe4-486e-a79e-5f703479eef6.png)

**Comment by DavitSo** [comment] 2023-03-23 05:32
Hi All,
Is there any update on this?
Question:
I see finishedRegistry.register(this, this._name) in dd-trace/opentracing/span.js, but I cant see unregister from there, can it be the cause of the leak?
![image](https://user-images.githubusercontent.com/45847601/227112445-2c1d6233-a1bd-4a25-b2e8-089bfa9d2c5b.png)

**Comment by Shoshvany** [comment] 2023-06-06 08:48
tried "vanilla" implementation with ver 4.1 (single high memory pod, single index JS):
`const datadog = require('dd-trace');
const { PubSub: GooglePubSub } = require('@google-cloud/pubsub');

const environment = 'staging';
const serviceName = 'serviceName';
const projectId = 'climacell-platform-staging';
const logger = console;

function initializeDatadog() {
    datadog.init({
        logInjection: true,
        service: serviceName,
        env: environment,
        logLevel: 'debug',
    });
}

function initializePubSubPulling() {
    const pubsub = new GooglePubSub({ projectId });

    const subscriberOptions = {
        ackDeadline: 100,
        flowControl: {
            maxMessages: 20,
            allowExcessMessages: false,
        },
    };

    const subscription = pubsub.subscription('memory-leak-test-subscription', subscriberOptions);

    logger.info(`Ready to receive messages`);

    async function errorHandler(error) {
        logger.error('Error in subscription', { error });
    }

    subscription.on('message', handler);
    subscription.on('error', errorHandler);

    let closed = false;

    function exitHandler() {
        if (!closed) {
            logger.info('Closing pubsub subscriber');
            subscription.removeListener('message', handler);
            subscription.removeListener('message', errorHandler);
            subscription.close();
            closed = true;
        }
    }

    process.on('exit', exitHandler);
    process.on('SIGINT', exitHandler);
    process.on('SIGUSR1', exitHandler);
    process.on('SIGUSR2', exitHandler);
}

async function handler(message) {
    message.ack();
    logger.info('handler called');
}

initializeDatadog();
initializePubSubPulling();
`

with -- inspect (node 16)

![image](https://github.com/DataDog/dd-trace-js/assets/3226528/a03c0e31-54a0-440c-8607-ee89a03d035a)
each test run with high rps and large payloads

checked one hour after each test
![image](https://github.com/DataDog/dd-trace-js/assets/3226528/e025db61-25f4-4850-9757-0a7f20b1fd3a)
![image](https://github.com/DataDog/dd-trace-js/assets/3226528/efdf32ee-a03f-4c0b-bb94-5bd06501dc9b)

Datadog objects increase during the load and barely change after
using version 2.1 for the same test 
![image](https://github.com/DataDog/dd-trace-js/assets/3226528/427f94d7-c9ec-4fdc-9274-cdead53be96f)

**Comment by rochdev** [comment] 2023-06-16 14:06
@Shoshvany Can you share the rest of your test setup? For example, how are you sending load to the app?

**Comment by rochdev** [comment] 2023-06-16 15:37
I tried to set up my own stress test, but I end up seeing a memory leak regardless of the version of dd-trace, and even without dd-trace, so I'm not sure how to properly look into the issue since it seems there is a leak in the PubSub library itself.

@Shoshvany I'll definitely need your test setup to investigate further.

In the meantime, I'll look into changes that happen between 2.10.0 and 2.11.0. There were changes to `http2` and `grpc-js` integrations which are used by PubSub, so the problem might be in one of those.

**Comment by Shoshvany** [comment] 2023-06-18 08:01
@rochdev 
I'm using another pod with a dedicated endpoint (that uses PubSub publish) and use BlazeMeter to generate load on that endpoint.

Its important to say that I use large PubSub payloads (~22k json) in order to see the problem

**Comment by Shoshvany** [comment] 2023-06-25 11:52
@rochdev, I think you are correct, 
added `tracer.use("grpc", false)` after `datadog.init` and memory leak disappeared

**Comment by mmarteauWoop** [comment] 2023-07-11 07:04
We experienced similar memory leaks on our apps. Disabling grpc plugin by using `DD_TRACE_DISABLED_PLUGINS=grpc` environment variable solved the problem.

I made a minimal reproduction to be sure that it was indeed the problem and not the google pubsub library itself:

```js
import {PubSub} from '@google-cloud/pubsub';

const pubsub = new PubSub()

try {
  await new Promise(resolve => setTimeout(resolve, 10000))
  await pubsub.createSubscription('localTopic', 'localSubscription')
  console.log('created subscription')
} catch (e) {
  console.log('subscription already exists')
}

const subscription = pubsub.subscription('localSubscription')

let i = 0
subscription.on('message', message => {
  i++
  message.ack()
})
```

I then publish 500 events, wait for a while and then send a massive 10k events.

Here is the result with `--require dd-trace/init`:

<img width="431" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/139209174/eee37032-490f-425f-8b25-98a990808a9a">
<img width="333" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/139209174/fa597ac4-098a-4096-be61-552549f92f1a">
<img width="392" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/139209174/eeff3675-d11b-414e-b403-9a94e38692cc">

And with grpc datadog plugin disabled environment variable:

<img width="423" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/139209174/66defc0c-fa5f-49f6-b783-fee49e22ba03">
<img width="335" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/139209174/215894b4-d304-468d-8165-922a66f447bd">
<img width="386" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/139209174/3a22899a-a37e-4955-88ab-0ab0bfd4195f">

As you can see the garbage collector fails to collect a lot of things with grpc plugin enabled. After checking with the profiler it's really obvious.

This is something quite annoying for us as it made us scale up on our pods for nothing...

**Comment by tlhunter** [comment] 2023-07-27 21:48
Can you upgrade to v4.7.0 / v3.28.0 / v2.41.0 and see if the memory leak is any better? In those releases we included a [big change to gRPC](https://github.com/DataDog/dd-trace-js/pull/3366) with the intent to fix the memory leak.

**Comment by tlhunter** [comment] 2023-12-18 22:48
Looks like this might have been solved by the aforementioned grpc changes. I'll close it for now but feel free to reopen if I'm off.

**Closed by tlhunter** 2023-12-18 22:48 UTC
Labels: bug, performance, integration-grpc
