### ISSUE TITLE
Traces lost connection with logs

### ISSUE THREAD

**Issue by chris-hinds** [DataDog/dd-trace-js#1912] opened 2022-03-16 15:35 UTC
**Describe the bug**
After updating to dd-trace `2.2.1` we noticed that traces in datadog lost their connection with the logs and vice versa.
We were able to reproduce the issue on `2.2.1` but not on `2.1.1` pointing to there being issue with the [2.2.0 release.](https://github.com/DataDog/dd-trace-js/releases/tag/v2.2.0)

**Environment**

* **Operation system:**
* **Node version: 14.18.2**
* **Tracer version: 2.2.1**
* **Agent version: **

**Comment by rochdev** [comment] 2022-03-16 15:55
Closing as this is a duplicate of #1908

**Closed by rochdev** 2022-03-16 15:55 UTC
Labels: bug
