### ISSUE TITLE
tracer.extract is a noop

### ISSUE THREAD

**Issue by sabrehagen** [DataDog/dd-trace-js#741] opened 2019-11-11 06:13 UTC
**Describe the bug**
The `tracer.extract` function is a noop in the `opentracing-javascript` [library](https://github.com/opentracing/opentracing-javascript/blob/master/src/tracer.ts#L178). This causes calls to `tracer.extract` not to function as described [in the documentation](https://datadog.github.io/dd-trace-js/interfaces/tracer.html#extract) and an empty `SpanContext` is always returned.

**Environment**

* **Tracer version:** 0.14.4
* **Agent version:** 0.15.0

**Comment by rochdev** [comment] 2019-11-11 15:13
`tracer.extract` is only a noop on the noop tracer which inherits OpenTracing directly without overriding its noop methods. In a real app where the tracer is enabled and initialized, a real implementation is used instead in our subclass.

Can you provide snippets of how/where you initialize the tracer and how you use `tracer.extact`?

**Comment by sabrehagen** [comment] 2019-11-16 02:35
This was encountered in our unit testing when we were checking `tracer.extract` was successfully extracing the trace from our carrier. This was running under `jest`. Would this cause the mock implementation to be chosen rather than the functional implementation?

**Comment by rochdev** [comment] 2019-11-18 20:02
It's definitely possible that Jest ends up mocking the tracer, causing the call to `init()` to actually be a no-op and the tracer never initializing, resulting in the default no-op implementation to be used. The tracer also patches the Node module system to hook in many places. Since Jest does the same thing, it's also possible there is some kind of conflict between the 2.

In general it may be possible to fix or at the very least work around the issue, but we need to first figure out exactly what causes the no-op implementation to be used.

Can you validate if the tracer is being mocked by Jest?

**Comment by rochdev** [comment] 2020-09-24 17:53
Closing this, please reopen if you are still having the issue and it's not caused by Jest mocking the tracer.

**Closed by rochdev** 2020-09-24 17:53 UTC
Labels: bug, community, core
