### ISSUE TITLE
Nextjs service not showing errors

### ISSUE THREAD

**Issue by awilson1801** [DataDog/dd-trace-js#1415] opened 2021-06-09 18:39 UTC
I recently updated a couple Nextjs apps to dd-trace-js 0.34.0 to take advantage of the tracing support for next. However, after upgrading I noticed that an entire separate service was created in APM. While this was not desired it would be acceptable if the new "next" service was properly showing errors in the "Errors Widget" (see below). I have two different services with the new tracer version and neither of them properly report errors in this widget. The original service that was created in the previous tracer version however does show these errors. Is this behavior expected?

Original service properly showing errors:
![image](https://user-images.githubusercontent.com/59579365/121410211-f8340b80-c927-11eb-9ec5-f7eb1eb7e981.png)

Newly created "Next" service without errors (same time period):
![image](https://user-images.githubusercontent.com/59579365/121410317-139f1680-c928-11eb-9b27-fc76225055ca.png)

**Comment by rochdev** [comment] 2021-06-09 18:56
Is this something you can minimally replicate? We do test errors and they are working in our tests, and for the top-level service it should be based on the status code, so having the additional Next span shouldn't make a difference there in theory.

**Comment by awilson1801** [comment] 2021-06-09 19:54
When you say "replicate" what do you mean, exactly? The use case here is I am trying to create SLIs from these metrics. Ideally, all spans and all errors would be contained in the same service. I suppose technically I can grab the errors from the top-level service (which doesn't identify endpoints properly so i'll have to create a custom metric) and grab the total count of requests from the "next" service (in order to avoid having to create a custom metric). It's just not very clean. If this behavior is expected you can close this and I'll work around it.

**Comment by rochdev** [comment] 2021-06-09 20:00
> When you say "replicate" what do you mean, exactly?

I meant reproduce, sorry for the confusion.

> If this behaviour is expected you can close this and I'll work around it.

It's expected with the way the code is currently written, but if you can't group errors properly because of it, it's definitely a behaviour we should change. Right now only actual exceptions thrown from Next will be caught as error for the `-next` suffixed service. I'll have to check with the team what we could do here to improve this and get back to you.

**Comment by rochdev** [comment] 2021-06-21 19:02
@awilson1801 We're planning to merge the `http.request` and `next.request` spans soon, which should resolve your issue. It should make it to the next release, but at worst it would be the release after that one.

**Comment by jakemhiller** [comment] 2021-11-29 16:43
Should this be moved to a newer milestone? I don't think it has been resolved

**Comment by rochdev** [comment] 2021-12-03 20:02
It ended up requiring a breaking change to do this properly, so I'll move it to 2.0. We hope to ship this release by EOY or otherwise start of next quarter.

**Comment by rochdev** [comment] 2022-02-01 18:03
Fixed by #1802. It didn't make it into 2.0 but will be in the next release.

**Closed by rochdev** 2022-02-01 18:03 UTC
Labels: community, integrations
