### ISSUE TITLE
skip exprses static file  trace

### ISSUE THREAD

**Issue by wanglong167** [DataDog/dd-trace-js#400] opened 2018-12-20 08:40 UTC
skip exprses static file  trace

**Comment by rochdev** [comment] 2021-05-18 20:23
Duplicate of #350. While it's a different framework, the same [resolution](https://github.com/DataDog/dd-trace-js/issues/350#issuecomment-597403709) applies. Basically, the paths can be blocklisted if known in advance, or otherwise the trace can be dropped in a span hook with `span.setTag('manual.drop')`.

**Closed by rochdev** 2021-05-18 20:23 UTC
Labels: community, feature-request, integrations
