### ISSUE TITLE
Datadog Agent : Maximum call stack size exceeded

### ISSUE THREAD

**Issue by peterver** [DataDog/dd-trace-js#807] opened 2019-12-18 14:54 UTC
**Describe the bug**
When under larger load, the datadog agent will throw maximum call stack size exceeded errors, eventually leading to the nodejs process exitting (we have pm2 running, which will then autorestart the instance).

We've removed the dd-tracer for now as to make sure our system remains operational, but would like to be able to do APM tracing for our microservice.

**Environment**
Docker - Koa 2.10.0, clustered through PM2 (pm2-runtime)

* **Operation system:**
Alpine Linux

* **Node version:**
NodeJS 10.15

* **Tracer version:**
^0.16.2

* **Agent version:**
latest datadog/agent image

**Comment by rochdev** [comment] 2019-12-18 17:15
Can you share the stack trace of the error? This will help to see if there is any recursion happening.

**Comment by peterver** [comment] 2019-12-18 18:02
I'll try to reproduce it tomorrow ( As I already took out that deployment and no way to get back to those logs )

**Comment by rochdev** [comment] 2019-12-18 22:02
Please make sure to increase the value of `Error.stackTraceLimit` to something higher than 10 to make sure that we have a long enough stack trace.

**Comment by peterver** [comment] 2019-12-19 00:53
@rochdev how would I do this? Kinda new to the datadog setup (we have microservices running in both PHP and NodeJs, the only having this issue is our node microservices)

**Comment by rochdev** [comment] 2020-01-09 18:55
We have identified a similar issue with the `mysql2` plugin.

@peterver Are you using `mysql2` by any chance?

**Comment by gnomeria** [comment] 2020-01-23 10:52
We also encountered this error when we had a bug on our ORM with sequelize.

**Comment by rochdev** [comment] 2020-01-28 21:12
A fix was released for this issue for the `mysql2` plugin.

@peterver Can you confirm if you were using `mysql2` and if the problem is fixed with 0.17.0? Otherwise, can you share a stack trace?

@gnomeria Was it with `mysql2` as well?

**Comment by peterver** [comment] 2020-01-31 15:53
@rochdev we were indeed using mysql2 :)

**Comment by peterver** [comment] 2020-01-31 15:57
@rochdev I will take out some time next sprint to look into readding datadog for that node microservice, will come back to you after that. Thanks for the potential fix :D will let you know if this resolves the issue on our end

**Comment by andrewsouthard1** [comment] 2020-09-23 21:13
Hey @peterver - were you still seeing this issue? Closing for now but let us know if still occuring.

**Closed by andrewsouthard1** 2020-09-23 21:13 UTC
Labels: bug, community
