### ISSUE TITLE
Error with node integration

### ISSUE THREAD

**Issue by Seebiscuts** [DataDog/dd-trace-js#637] opened 2019-07-24 22:56 UTC
Adding dd-trace to a graphql gateway application ( node.js app) is throwing error. 

Here is the stack trace
`TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at DatadogSpan._addTags (node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:123:14)
    at DatadogSpan.Span.addTags (node_modules/opentracing/lib/span.js:106:14)
    at DatadogTracer._startSpan (node_modules/dd-trace/packages/dd-trace/src/opentracing/tracer.js:81:10)
    at DatadogTracer.Tracer.startSpan (node_modules/opentracing/lib/tracer.js:61:21)
    at Object.wrapMiddleware (node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:93:25)
    at callHandle (node_modules/dd-trace/packages/datadog-plugin-router/src/index.js:108:14)
    at node_modules/dd-trace/packages/datadog-plugin-router/src/index.js:64:14
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (node_modules/express/lib/router/index.js:317:13)`

**Environment**

* **Operation system:**  Mac OS-X
* **Node version:** 12.6.0 
Note: When I downgraded node to 11.0.0, everything works, no errors.
As per the docs, node version >= 8 is supported so I used latest node ( 12.6.0)
* **Tracer version:** 0.13.1 

Does dd-trace support Node.Js version 12 ?
Also, our node.js uses Apollo graphql server, do we have explict support for the apollo-Graphql ?

**Comment by Seebiscuts** [comment] 2019-07-24 23:38
Update: 
No errors with Node version 12.7.0 and dd-trace version 0.13.0.

**Comment by rochdev** [comment] 2019-07-25 18:02
Looks like a regression. It will be fixed for the next release.

About Apollo, it is supported out of the box by the `graphql` integration.

**Closed** 2019-07-25 18:24 UTC
Labels: bug, community
