### ISSUE TITLE
docs: How does tracing work under the hood?

### ISSUE THREAD

**Issue by seanyu4296** [DataDog/dd-trace-js#1268] opened 2021-03-15 11:03 UTC
# Background
I am using this library https://github.com/vpulim/node-soap/ in tandem with express and I noticed the `SpanContext` disappears when the library handles the request. It disappears specifically in this line of the code (https://github.com/vpulim/node-soap/blob/2b1e8bd81519607127248b78c896a7043f9b9ef0/src/server.ts#L276).

Is it because it is in the callback?  I've been looking around the whole day on how to debug it and how maybe I can add tracing support myself and sanely debug it, but I end up quite confused on how things actually work. I saw there is an express plugin that seems top patch express but not sure how it is applied. 

Overall, I am not sure how to go about debugging since I'm basing my knowledge on mostly assumptions. I think docs or guides will greatly help.

# Questions
1. Are there docs on how tracing works under the hood? How does it propagate or resolve the `SpanContext`, `traceId`, `spanId`?
2. Are there docs on how plugins work so maybe possibly I and the community can also debug and build plugins?

**Comment by rochdev** [comment] 2021-03-15 17:48
> Are there docs on how tracing works under the hood? How does it propagate or resolve the SpanContext, traceId, spanId?

There aren't as we've been mostly focused on keeping things simple and everything working out of the box. We're planning improvements to the API in the coming months and will be in a better position to explain how everything works within the tracer at that point.

For context propagation, basically we have what we call the [scope manager](https://github.com/DataDog/dd-trace-js/blob/e6acf12932e6f497d34b03f007ec2507c2a4ae54/packages/dd-trace/src/scope/async_resource.js), which is in charge of propagating context both synchronously but also asynchronously, for example when using promises, timers, or native Node modules like `http`. In order to keep track of a request across these constructs we use [async_hooks](https://nodejs.org/api/async_hooks.html) which is a built-in Node module able to track which asynchronous execution context created another one. We can then store the current span on the asynchronous resource of this context.

In general, this works well and handles 99% of cases, but there are cases where libraries might do something that doesn't play well with `async_hooks` or with our integrations. The ones we know about are already addressed in additional integrations for these cases, but there can be others, like potentially the issue you're having right now.

> Are there docs on how plugins work so maybe possibly I and the community can also debug and build plugins?

No docs as right now there are no public APIs to build plugins and they are all internal. For the most part all plugins use the same pattern, so it should be straightforward to make a new plugin based on existing ones. Ideally this would be better documented, but as mentioned above we prefer to have a well defined API first which is in the works.

> Is it because it is in the callback?

Possible but that callback is an event listener on the request which should restore the correct context since that's handled by the `http` plugin. Can you give more details about what the problem is with tracer? Are you seeing spans not connected together as separate traces? Are you not getting traces at all?

**Comment by seanyu4296** [comment] 2021-03-16 03:36
@rochdev Thanks so much for taking the time to reply! Sorry for the late reply, I'm at GMT+8

> There aren't as we've been mostly focused on keeping things simple and everything working out of the box. We're planning improvements to the API in the coming months and will be in a better position to explain how everything works within the tracer at that point.

Got it! Good luck and really looking forward to it! Let me know if there's some help that I can contribute to

> For context propagation, basically we have what we call the scope manager, which is in charge of propagating context both synchronously but also asynchronously, for example when using promises, timers, or native Node modules like http. In order to keep track of a request across these constructs we use async_hooks which is a built-in Node module able to track which asynchronous execution context created another one. We can then store the current span on the asynchronous resource of this context. In general, this works well and handles 99% of cases, but there are cases where libraries might do something that doesn't play well with async_hooks or with our integrations. The ones we know about are already addressed in additional integrations for these cases, but there can be others, like potentially the issue you're having right now.

Will this implementation change in the next coming months or in the foreseeable future? Asking before I try to dive in and grok how things work. 

> No docs as right now there are no public APIs to build plugins and they are all internal. For the most part all plugins use the same pattern, so it should be straightforward to make a new plugin based on existing ones. Ideally this would be better documented, but as mentioned above we prefer to have a well defined API first which is in the works.

Is it correct to assume that plugins are all internally developed and there's no way to add in custom plugins except to fork the library or submit a PR and get approved to add a custom one?


> Possible but that callback is an event listener on the request which should restore the correct context since that's handled by the http plugin. Can you give more details about what the problem is with tracer? Are you seeing spans not connected together as separate traces? Are you not getting traces at all?

I was getting one whole line of trace (see below).  When I call `tracer.scope().active()` in one of my soap service functions (just think of this a function thats selectively called), it returns `null`. I  tried to add a `tracer.trace` in one of my soap service functions it creates a different `traceId`. 
![Screen Shot 2021-03-16 at 11 27 51 AM](https://user-images.githubusercontent.com/11349232/111251700-b65a3880-864a-11eb-8c34-badfae6b1a1c.png)


In the below code, the first log has an active scope, but if its inside the `on('end')` it returns `null`
```
// this is transpiled code from https://github.com/vpulim/node-soap/blob/2b1e8bd81519607127248b78c896a7043f9b9ef0/src/server.ts#L275 
// when you install the package since it is typescript
console.log('Outside of sourceOnEnd:', req._datadog.tracer.scope().active()) // this does not return null
source.on('end', function () {
    var xml = Buffer.concat(chunks_1).toString();
    console.log('SourceOnEnd2:', req._datadog.tracer.scope().active())  // this returns null
    _this_1._processRequestXml(req, res, xml);
});
```

**Comment by seanyu4296** [comment] 2021-03-16 03:42
Not so related to the current topic, but can i also ask what is `carrier` in `tracer.inject` and `tracer.extract`? How are those two functions used in the real world? @rochdev Thanks!

**Comment by rochdev** [comment] 2021-03-17 01:00
> Will this implementation change in the next coming months or in the foreseeable future? Asking before I try to dive in and grok how things work.

The bulk of it won't change as our scope manager is just a thin layer on top of the official Node construct for context propagation. Unless Node changes how it handles propagation, it's very unlikely that our logic will change much.

> Is it correct to assume that plugins are all internally developed and there's no way to add in custom plugins except to fork the library or submit a PR and get approved to add a custom one?

Right now this is correct but we'll be working on the ability to register plugins externally in the coming months. In the meantime, the only way is to fork and/or submit a PR, and we definitely welcome PRs and this would be the recommended approach instead of maintaining a fork.

However, looking at the `node-soap` code, it should work just with the `http` plugin so it looks like this could be a bug or a misconfiguration. Because of this, I would recommend holding off opening a PR for now until a bug is ruled out to avoid writing a plugin that may end up not being needed.

Is the issue something you are able to reproduce with a minimal snippet that I could try?

> Not so related to the current topic, but can i also ask what is carrier in tracer.inject and tracer.extract? How are those two functions used in the real world?

These 2 functions are used to propagate the distributed tracing context from one service to another. On the client side, `inject` is called to add the context to a carrier that will be sent to the other service, and then `extract` is used in that other service to restore the tracing context from the carrier as the parent of the trace created in that service. A carrier can be any object that will be available on both sides of the request. For example, for HTTP requests, the carrier is the headers. Both methods support a few propagators that know how to handle specific carrier, but the main one is `text_map` which simply adds the context as properties of an object, for example `options.headers`.

**Comment by seanyu4296** [comment] 2021-03-17 07:44
> However, looking at the node-soap code, it should work just with the http plugin so it looks like this could be a bug or a misconfiguration. Because of this, I would recommend holding off opening a PR for now until a bug is ruled out to avoid writing a plugin that may end up not being needed.
Is the issue something you are able to reproduce with a minimal snippet that I could try?

I'll create a minimal repository/sandbox reproducing the issue by EOD Friday.

> These 2 functions are used to propagate the distributed tracing context from one service to another. On the client side, inject is called to add the context to a carrier that will be sent to the other service, and then extract is used in that other service to restore the tracing context from the carrier as the parent of the trace created in that service. A carrier can be any object that will be available on both sides of the request. For example, for HTTP requests, the carrier is the headers. Both methods support a few propagators that know how to handle specific carrier, but the main one is text_map which simply adds the context as properties of an object, for example options.headers.

Ohhh this one right for the http (https://github.com/DataDog/dd-trace-js/blob/e6acf12932e6f497d34b03f007ec2507c2a4ae54/packages/dd-trace/src/opentracing/propagation/http.js).  gotcha I think I have a better grasp or high overview on which is which and what are the moving parts of the library.

**Comment by justinlesko** [comment] 2021-04-12 15:42
I encountered a similar problem to @seanyu4296 while using the [strong-soap](https://github.com/strongloop/strong-soap) library. I've found a suitable workaround for now; if you look [here](https://github.com/strongloop/strong-soap#server-logging) you'll see that you can pass in the original `req` into the service. The `req` is already enriched by DataDog, and you can use the private DataDog data members to set the scope. Please see an example of this below:

```javascript
const myExampleService = {
  MyExampleService: {
    MyExample: {
      exampleFunctions: function(payload, callback, headers, req) {
        tracer.scope().activate(req._datadog.span, () => {
          const foo = tracer.trace('span_func1', () => {
            return myFunc1(payload);
          });
          tracer.trace('span_func2', () => {
            return myFunc2(foo);
          });
          tracer.trace('span_callback', () => {
            return callback();
          });
        });
      }
    }
  }
};
```

**Comment by tlhunter** [comment] 2023-12-18 22:06
I'm trying to close out old issues and it looks like @seanyu4296's original questions were answered. I'll close this for now but if you feel it's deserving of more attention then feel free to reopen.

**Closed by tlhunter** 2023-12-18 22:06 UTC
Labels: feature-request
