### ISSUE TITLE
Issue setting up express plugin settings 

### ISSUE THREAD

**Issue by kumaraksi** [DataDog/dd-trace-js#978] opened 2020-06-06 23:00 UTC
**Describe the bug**
I am facing the following issues while trying to setup the express plugin - 
1. `middleware:false` does not seem to work.
2. Blacklisting based on URL is not working. (I want to disable APM for `/health/check` )

Plugin settings - 
```
    tracer.use('express', {
        blacklist: [/.*\/health\/check/],
        middleware: false,
    });
```

Screenshots - 

1. middleware still visible in DD monitoring dashboard - 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/1006860/83955939-aceca600-a858-11ea-92cc-4fc61aafd357.png">

2. Blacklisted URL is also visible - 
![image](https://user-images.githubusercontent.com/1006860/83956072-52544980-a85a-11ea-828b-28fac5424071.png)

**Environment**

* **Node version:** node:10.13
* **Tracer version:** 0.21

**Comment by kumaraksi** [comment] 2020-06-06 23:01
It will be great if someone can guide me on this. 🙏

**Comment by rochdev** [comment] 2020-06-09 18:58
Can you share the top of the entry point file where the tracer is imported/initialized? Usually when the configuration is ignored it's because of an ordering issue, for example something being imported before the tracer is initialized. There was however a similar report for the `graphql` plugin and I'm starting to wonder if there is a regression in the instrumenter. Confirming that the order is correct would help validate that.

**Comment by andrewsouthard1** [comment] 2020-09-23 20:59
@kumaraksi - going to close this out for now, if you have any questions and want to dig further please reach out.

**Closed by andrewsouthard1** 2020-09-23 20:59 UTC
Labels: bug, community, integrations

**Comment by AlaaAttya** [comment] 2020-11-05 18:39
hi @rochdev 

i'm facing the same issue right now. you can find the entry file of my service is like this. 
these lines are even added before all the imports

```
'use strict';

const tracer = require('dd-trace').init({
    plugins: false,
    startupLogs: true,
    debug: DD_DEBUG_ENABLED,
    runtimeMetrics: DD_RUNTIME_METRICS_ENABLED,
    service: DD_SERVICE,
    env: DD_ENV,
    analytics: true
});
tracer.use('express', {
    middleware: false,
    blacklist: ['/health/check']
});

// all the imports go after this lines
```

**Comment by AlaaAttya** [comment] 2020-11-06 15:08
I have managed to fix it by a very simple change. setting the `plugins: false`
From what i see is that by default the library is loading the plugins asynchronously which might override the configs for the plugin and setting them to the default ones


below is the code that made it to work

```
'use strict';

const tracer = require('dd-trace').init({
    plugins: false,
    startupLogs: true,
    debug: DD_DEBUG_ENABLED,
    runtimeMetrics: DD_RUNTIME_METRICS_ENABLED,
    service: DD_SERVICE,
    env: DD_ENV,
    analytics: true
});
tracer.use('express', {
    plugins: false, // here's the change that made it work
    middleware: false,
    blacklist: [/.*\/health\/check/] // and this one also
});

// all the imports go after these lines
```
