### ISSUE TITLE
`net` plugin causes tcp socket buffer corruption

### ISSUE THREAD

**Issue by jon-whit** [DataDog/dd-trace-js#1311] opened 2021-04-15 14:12 UTC
**Describe the bug**
I have an application that sends batches of messages out over a tcp connection through NATS (using the NATS protocol). With `dd-trace` initialized and running with it's default plugins (net, dns, etc..), I get socket buffer corruption with the inbound bytes coming in on the tcp socket. If I disable the `net` plugin or remove `dd-trace` altogether, my application works just fine. I don't have a minimally working example at this time. But I do have a reproducible example with a NATS integration.

Are there some quick and dirty checks we can do on the plugin implementation to identify such an issue? If not, I can give specifics about the application and show tcpdump output from the NATS protocol and compare with behavior from the app.

**Environment**
Any

* **Operation system:** Tested on Mac OSX (Catalina), Kubernetes, within a linux docker image
* **Node version:** 14.16.1 (LTS)
* **Tracer version:** ^0.32.0

**Comment by rochdev** [comment] 2021-04-16 15:36
> Are there some quick and dirty checks we can do on the plugin implementation to identify such an issue?

Not really, you would have to basically try to track where the buffer is getting corrupted in the internals.

Can you share the reproducible example? If not, can you remove all business logic and reduce it down to something you could share? The only other option since this is not something we've seen before would be if you can pinpoint where the issue is so that we can then reproduce it on our end.

**Comment by jon-whit** [comment] 2021-04-16 18:44
@rochdev I'm working on a minimal example, but it's pretty non-trivial as you could image :). I've definitely confirmed though that it's the `net` plugin causing buffer corruption. If I disable the `net` plugin all the buffer corruption behavior disappears from my application.

**Comment by jon-whit** [comment] 2021-04-20 20:52
@rochdev here's a minimized sample project demonstrating the issue:
https://github.com/jon-whit/dd-trace-net-bug

Whatever you guys are doing with the tcp packet buffers is causing corruption. This affects `dd-trace` package versions 0.30.6 and earlier from what I can tell.

I have tcpdump information from the NATS server to confirm the suspicion that it is indeed `dd-trace` causing the problem. But I have confirmed it quite easily just by disabling the `net` plugin and the issue goes away. Upgrading to 0.31.x or later fixes the issue as far as I can tell. Ya'll should publish a patch fix to 0.30.x and earlier packages, as I am sure there are handfuls of people using it.

**Comment by rochdev** [comment] 2021-04-21 15:21
I was able to reproduce with 0.30.6 but not with the latest version as you pointed out. We always recommend using the latest version of the tracer, and we don't currently maintain older versions, so if you can confirm that it works for you with the latest version (currently 0.32.1) then I'd say we can simply close this issue and consider it resolved.

**Comment by jon-whit** [comment] 2021-04-21 17:22
Would it at least be worth making an announcement about or sending a customer wide email for DataDog customers using `dd-trace`?

**Comment by bengl** [comment] 2021-04-23 16:23
We're currently reviewing our process for announcing that kind of information. In the meantime, I'll close this issue since it's resolved.

**Closed by bengl** 2021-04-23 16:23 UTC
Labels: bug, community, integrations
