### ISSUE TITLE
Instrumentation for Mocha >=5.2.0 is broken

### ISSUE THREAD

**Issue by jodigiordano** [DataDog/dd-trace-js#2595] opened 2022-12-06 18:49 UTC
**Expected behaviour**

Mocha tests should run.

**Actual behaviour**

All Mocha tests are skipped.

**Environment**

* **Operation system:** GNU/Linux Debian 11
* **Node.js version:** v16.17.1
* **Tracer version:** 3.9.0

**The issue**

The culprit is [this new piece of code](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-instrumentations/src/mocha.js#L308):

* It overrides the original `Mocha.run`.
* It sends messages (`ci:mocha:configuration` and `ci:mocha:test-suite:skippable`) and will run the original `Mocha.run` upon receiving the responses.
* From what I understand, [the Mocha plugin](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-mocha/src/index.js) should listen to those messages but it doesn't.

**Comment by juan-fernandez** [comment] 2022-12-07 10:14
> **Expected behaviour**
> 
> Mocha tests should run.
> 
> **Actual behaviour**
> 
> All Mocha tests are skipped.
> 
> **Environment**
> 
> * **Operation system:** GNU/Linux Debian 11
> * **Node.js version:** v16.17.1
> * **Tracer version:** 3.9.0
> 
> **The issue**
> 
> The culprit is [this new piece of code](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-instrumentations/src/mocha.js#L308):
> 
> * It overrides the original `Mocha.run`.
> * It sends messages (`ci:mocha:configuration` and `ci:mocha:test-suite:skippable`) and will run the original `Mocha.run` upon receiving the responses.
> * From what I understand, [the Mocha plugin](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-mocha/src/index.js) should listen to those messages but it doesn't.

hi @jodigiordano ! Thanks for reporting this issue.

I can't reproduce it 🤔. Could you help me by providing: 

1. a small reproducible case
2. if 1. is not possible, the dd-trace config you're using to run mocha: are you using `NODE_OPTIONS` ?
3. any mocha non-default config you might be using

**Comment by juan-fernandez** [comment] 2022-12-07 10:30
> > **Expected behaviour**
> > Mocha tests should run.
> > **Actual behaviour**
> > All Mocha tests are skipped.
> > **Environment**
> > 
> > * **Operation system:** GNU/Linux Debian 11
> > * **Node.js version:** v16.17.1
> > * **Tracer version:** 3.9.0
> > 
> > **The issue**
> > The culprit is [this new piece of code](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-instrumentations/src/mocha.js#L308):
> > 
> > * It overrides the original `Mocha.run`.
> > * It sends messages (`ci:mocha:configuration` and `ci:mocha:test-suite:skippable`) and will run the original `Mocha.run` upon receiving the responses.
> > * From what I understand, [the Mocha plugin](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-mocha/src/index.js) should listen to those messages but it doesn't.
> 
> hi @jodigiordano ! Thanks for reporting this issue.
> 
> I can't reproduce it 🤔. Could you help me by providing:
> 
> 1. a small reproducible case
> 2. if 1. is not possible, the dd-trace config you're using to run mocha: e.g. are you using `NODE_OPTIONS` to init dd-trace?
> 3. any mocha non-default config you might be using
> 4. any dd-trace error log you see when running mocha

I found a bug where if dd-trace could not be initialized correctly the tests are not running at all. I'll be pushing a fix right away, but I want to confirm that this is what's happening to you.

**Comment by jodigiordano** [comment] 2022-12-07 18:09
Hi @juan-fernandez ! Thank you very much for looking into this. I confirm that:

* I am in fact in a situation where `dd-trace` is not initialized, as we enable/disable `dd-trace` in our tests via a flag. :scream_cat:
* The fix you produced solve my issue! :rocket:

Cheers! :beers:

**Comment by juan-fernandez** [comment] 2022-12-08 21:44
#2599 is merged. The fix will be in the next release, which will be tomorrow 😄

**Closed** 2022-12-08 21:44 UTC
Labels: bug, ci-app

**Comment by juan-fernandez** [comment] 2022-12-09 19:00
> #2599 is merged. The fix will be in the next release, which will happen tomorrow 😄

https://github.com/DataDog/dd-trace-js/releases/tag/v3.9.3 and https://github.com/DataDog/dd-trace-js/releases/tag/v2.22.3 should include this fix 😄
