### ISSUE TITLE
Cannot read properties of undefined (reading '_tags')

### ISSUE THREAD

**Issue by Grmiade** [DataDog/dd-trace-js#2201] opened 2022-07-20 11:48 UTC
When we launch our service configured with `dd-trace` in local development (with DD_TRACE_ENABLED set to false) with the last `2.11.0` version, we encounter this error:
```
TypeError: Cannot read properties of undefined (reading '_tags')
    at addError (/usr/src/app/.yarn/unplugged/dd-trace-npm-2.11.0-679f9bd452/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:56:34)
```

Regression probably introduced by https://github.com/DataDog/dd-trace-js/pull/2177/files#diff-cb1c4e2e401f2670c4f6bb1dcc1a01932efa069ed5f10016a5f9c55db64aab28

Downgrade to `2.10.0` resolve the issue.

**Environment**

* **Node.js version:** 18.5.0
* **Tracer version:** `2.11.0`

**Comment by rochdev** [comment] 2022-07-20 15:39
@Grmiade Can you provide a reproduction? It shouldn't be possible that `_spanContext` is undefined so I'm not sure how to reproduce this.

**Comment by Grmiade** [comment] 2022-07-20 16:16
@rochdev You can try that:

```javascript
const tracer = require("dd-trace");
tracer.init();
tracer.use("graphql", { depth: 0 }); // It works if I delete this line

const { ApolloServer, gql } = require("apollo-server");
const { buildSubgraphSchema } = require("@apollo/subgraph");

const server = new ApolloServer({
  schema: buildSubgraphSchema([
    { resolvers: {}, typeDefs: gql`type Query { hello: String }` },
  ]),
});

server.listen().then(serverInfo => console.log(`🚀  Server ready at ${serverInfo.url}`));
```

https://cuboid-stump-health.glitch.me

**Comment by rochdev** [comment] 2022-07-20 18:13
I get the following error when trying to run this snippet:

```
const sdlRules = specifiedRules_1.specifiedSDLRules.filter(rule => !skippedSDLRules.includes(rule));
                                                    ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at Object.<anonymous> (/Users/rochdevost/go/src/github.com/DataDog/dd-trace-js/node_modules/@apollo/subgraph/dist/schema-helper/buildSchemaFromSDL.js:32:53)
```

Do I need to do anything specific before running this?

**Comment by Grmiade** [comment] 2022-07-20 18:56
@rochdev You have to install the `graphql` package also.

**Comment by rochdev** [comment] 2022-07-21 02:59
It turns out the issue is not isolated to GraphQL but is a bug in the plugin manager specifically when the tracer is disabled. I'm working on a fix that will be released as soon as possible.

**Closed** 2022-07-26 18:51 UTC
Labels: bug
